import type { Plugin, TAbstractFile } from 'obsidian'
import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import type { PMSettings, Project, ResolvedProjectConfig, StatusConfig, Task } from '../types'
import { DEFAULT_SETTINGS, makeId, makeProject, makeTask } from '../types'
import { today } from '../dates'
import { isTerminalStatus } from '../utils'
import { archiveTask as doArchiveTask, unarchiveTask as doUnarchiveTask } from './ArchiveOps'
import { resolveProjectConfig } from './ProjectConfig'
import { computeSchedule } from './Scheduler'
import {
  findParentId,
  findTaskById,
  indexAddSubtree,
  indexRemoveSubtree,
  indexSetParent,
  rebuildTaskIndex
} from './TaskIndex'
import {
  addTaskToTree,
  cloneTaskSubtree,
  deleteTaskFromTree,
  flattenTasks,
  moveTaskInTree,
  updateTaskInTree
} from './TaskTreeOps'
import { hydrateProjectFromFrontmatter, hydrateTaskFromFile, hydrateTasks } from './YamlHydrator'
import { FRONTMATTER_KEY, TASK_FRONTMATTER_KEY, parseFrontmatter, stripAutoGeneratedContent } from './YamlParser'
import {
  buildTaskFrontmatter,
  serializeProject,
  serializeTask,
  taskFilePath,
  TASK_SLUG_MAX_LENGTH
} from './YamlSerializer'
import { ensureFolder, moveTaskAttachmentFolder } from './vaultFs'
import type { ImportNoteOptions, TaskSource } from './TaskSource'

/**
 * 'fm' — only frontmatter changed; body content is unaffected. Save path can
 * use processFrontMatter and skip reading the body.
 * 'full' — body content depends on the change (description edited, file
 * renamed, archived flag flipped, structural relationships moved). Save path
 * rewrites the whole file atomically via vault.process.
 */
type DirtyKind = 'fm' | 'full'

/** Patches that touch any of these require rewriting the body, not just the frontmatter. */
function patchNeedsBodyRewrite(patch: Partial<Task>): boolean {
  // `subtasks` changes the parent's `## Subtasks` list, which lives in the body.
  return patch.description !== undefined || patch.archived !== undefined || patch.subtasks !== undefined
}

/** A basename of this exact length that prefixes the title's slug is kept as-is. */
const LEGACY_SLUG_CAP = 40

/**
 * Pick a save path. New tasks get the bare slug; an existing file is left where
 * it is when its name still matches the title, so an unchanged title isn't renamed.
 */
function resolveTaskPath(task: Task, folder: string, previousPath: string | undefined): string {
  const desired = taskFilePath(task.title, folder)
  if (!previousPath) return desired
  const desiredBasename = desired.slice(desired.lastIndexOf('/') + 1).replace(/\.md$/, '')
  const previousFolder = previousPath.slice(0, previousPath.lastIndexOf('/'))
  const previousBasename = previousPath.slice(previousPath.lastIndexOf('/') + 1).replace(/\.md$/, '')
  if (previousFolder !== folder) return desired
  const legacyBasename = `${desiredBasename}-${task.id.slice(0, 8)}`
  if (previousBasename === legacyBasename) return previousPath
  if (previousBasename.length === LEGACY_SLUG_CAP && previousBasename === desiredBasename.slice(0, LEGACY_SLUG_CAP)) {
    return previousPath
  }
  return desired
}

/** Thrown when saving a task would collide with an existing file in the vault. */
export class TaskFileNameConflictError extends Error {
  constructor(public readonly path: string) {
    super(`A note named "${fileNameFromPath(path)}" already exists.`)
    this.name = 'TaskFileNameConflictError'
  }

  get fileName(): string {
    return fileNameFromPath(this.path)
  }
}

function fileNameFromPath(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.md$/, '')
}

/** The vault-relative parent folder of a path (`''` for a vault-root file). */
function parentDirOf(path: string): string {
  const idx = path.lastIndexOf('/')
  return idx > 0 ? path.slice(0, idx) : ''
}

/**
 * Handles all read/write operations against the Obsidian vault.
 *
 * Storage layout:
 *   Projects/<ProjectName>.md         — project metadata (no task data)
 *   Projects/<ProjectName>/<slug>.md  — one .md per task
 *
 * The in-memory Project.tasks tree is assembled on load from individual
 * task files and remains unchanged for views.
 */
export class ProjectStore implements TaskSource {
  /** Per-project promise chains to serialize concurrent saves */
  private saveQueues = new Map<string, Promise<void>>()

  /**
   * Task IDs whose .md file needs writing on the next save, with the kind of
   * write required ('fm' for frontmatter-only, 'full' for whole-file rewrite).
   * Tasks with no filePath are always written as 'full'.
   */
  private dirtyTasks = new Map<string, Map<string, DirtyKind>>()

  /**
   * Tasks and projects whose in-memory `description` is known to match disk
   * (either we just wrote it, or we loaded it from the body). Cache-loaded
   * objects start out absent — their description is empty until loadTaskBody /
   * loadProjectBody fills it, or until a 'full' save reads it back inline.
   */
  private hydratedBodies = new WeakSet<Task | Project>()

  /**
   * Projects already loaded this session, keyed by file path. The cached
   * object is the in-memory canonical copy: mutators keep it current, every
   * successful save re-points the entry at the saved object, and external
   * (non-self-write) vault events drop the entry so the next load re-reads.
   */
  private projectCache = new Map<string, Project>()

  /**
   * Paths we've just written, created, or trashed ourselves, timestamped.
   * The view's modify/delete listeners consume markers to skip reloads; the
   * cache invalidation listeners peek at them without consuming.
   * Stale entries (older than the window) are treated as never-marked.
   */
  private selfWrites = new Map<string, number>()
  private static readonly SELF_WRITE_WINDOW_MS = 5000

  constructor(
    private app: App,
    private getSettings: () => PMSettings = () => DEFAULT_SETTINGS
  ) {}

  configFor(project: Project): ResolvedProjectConfig {
    return resolveProjectConfig(project, this.getSettings())
  }

  private statusesFor(project: Project): StatusConfig[] {
    return this.configFor(project).statuses
  }

  // ─── Dirty tracking ───────────────────────────────────────────────────────

  private markDirty(project: Project, taskIds: Iterable<string>, kind: DirtyKind): void {
    let map = this.dirtyTasks.get(project.filePath)
    if (!map) {
      map = new Map()
      this.dirtyTasks.set(project.filePath, map)
    }
    for (const id of taskIds) {
      // Upgrade-only: 'full' wins over 'fm', never the reverse.
      if (map.get(id) === 'full') continue
      map.set(id, kind)
    }
  }

  private markSubtreeDirty(project: Project, taskId: string, kind: DirtyKind): void {
    const task = findTaskById(project, taskId)
    if (!task) return
    this.markDirty(project, [taskId], kind)
    for (const ft of flattenTasks(task.subtasks)) {
      this.markDirty(project, [ft.task.id], kind)
    }
  }

  private markAllDirty(project: Project, kind: DirtyKind): void {
    const ids: string[] = []
    for (const ft of flattenTasks(project.tasks)) ids.push(ft.task.id)
    this.markDirty(project, ids, kind)
  }

  private clearDirty(project: Project): void {
    this.dirtyTasks.delete(project.filePath)
  }

  // ─── Self-write tracking ──────────────────────────────────────────────────

  private markSelfWrite(path: string): void {
    // Created files have no consumer, so sweep expired markers before they pile up.
    if (this.selfWrites.size > 256) {
      const cutoff = Date.now() - ProjectStore.SELF_WRITE_WINDOW_MS
      for (const [p, t] of this.selfWrites) {
        if (t < cutoff) this.selfWrites.delete(p)
      }
    }
    this.selfWrites.set(path, Date.now())
  }

  /** Returns true if we wrote this path recently. Consumes the marker either way. */
  consumeSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    if (ts === undefined) return false
    this.selfWrites.delete(path)
    return Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /** Like consumeSelfWrite, but non-destructive — view listeners still need the marker. */
  private peekSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    return ts !== undefined && Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /**
   * Wire vault events that drop cached projects on external changes. Call once
   * from onload, before any view registers listeners — these must run first so
   * a view's reload after an external edit misses the stale cache entry.
   */
  registerCacheInvalidation(plugin: Plugin): void {
    // create/modify: route qualifying external pm-task files to ingestion first
    // (it captures the owning project synchronously, before invalidation could
    // drop it), then invalidate the cache for external project-file edits.
    const onChange = (file: TAbstractFile): void => {
      if (file instanceof TFile) void this.handleExternalTaskChange(file)
      this.invalidateForPath(file.path)
    }
    plugin.registerEvent(this.app.vault.on('create', onChange))
    plugin.registerEvent(this.app.vault.on('modify', onChange))
    plugin.registerEvent(this.app.vault.on('delete', (file) => this.invalidateForPath(file.path)))
    plugin.registerEvent(
      this.app.vault.on('rename', (file, oldPath) => {
        // A rename of a loaded project file rebinds it in place (name + tasks
        // folder) instead of dropping it; handleExternalRename re-keys the cache.
        if (file instanceof TFile && this.projectCache.has(oldPath)) {
          void this.handleExternalRename(oldPath, file)
          return
        }
        this.invalidateForPath(file.path)
        this.invalidateForPath(oldPath)
      })
    )
  }

  private invalidateForPath(path: string): void {
    if (this.projectCache.size === 0) return
    if (this.peekSelfWrite(path)) return
    for (const key of this.projectCache.keys()) {
      if (path === key || path.startsWith(key.replace(/\.md$/, '_tasks') + '/')) {
        this.projectCache.delete(key)
      }
    }
  }

  // ─── Folder helpers ────────────────────────────────────────────────────────

  async ensureFolder(folderPath: string): Promise<void> {
    await ensureFolder(this.app, folderPath)
  }

  /** Get the task subfolder path for a project */
  private projectTaskFolder(project: Project): string {
    return project.filePath.replace(/\.md$/, '_tasks')
  }

  // ─── Load ──────────────────────────────────────────────────────────────────

  /**
   * Load every project in the vault. Since INT-014 the `folder` argument is only
   * a create-time default (seeded so a fresh vault has somewhere to put its first
   * project); it no longer bounds discovery. Projects are found vault-wide via
   * `discoverProjects`, so a project filed under any category subfolder shows up.
   */
  async loadAllProjects(folder: string): Promise<Project[]> {
    // Keep the default folder around so first-run flows have a home to write to.
    await this.ensureFolder(folder)
    return this.discoverProjects()
  }

  /**
   * Find every `pm-project: true` file anywhere in the vault, not just under a
   * configured root (INT-014, R9). Uses metadataCache to skip non-project files
   * cheaply; on a cache miss the file is read and filtered by `loadProject`.
   */
  async discoverProjects(): Promise<Project[]> {
    const candidates: TFile[] = []
    for (const file of this.app.vault.getMarkdownFiles()) {
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      // A resolved cache that isn't a project lets us skip the read; a cache miss
      // (cached == null) still needs loadProject to read and decide.
      if (cached && cached[FRONTMATTER_KEY] !== true) continue
      candidates.push(file)
    }
    const loaded = await Promise.all(candidates.map((f) => this.loadProject(f)))
    const projects = loaded.filter((p): p is Project => p !== null)
    return projects.sort((a, b) => a.title.localeCompare(b.title))
  }

  /**
   * Resolve the vault-relative directory a project lives in: its declared `path`
   * frontmatter when present and non-blank, otherwise the file's actual parent
   * folder (legacy fallback, R11). Task files resolve against this directory.
   */
  projectDirectory(project: Project): string {
    const declared = project.path?.trim()
    if (declared) return declared
    const fp = project.filePath
    const idx = fp.lastIndexOf('/')
    return idx > 0 ? fp.slice(0, idx) : ''
  }

  async loadProject(file: TFile): Promise<Project | null> {
    const cachedProject = this.projectCache.get(file.path)
    if (cachedProject) return cachedProject
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the disk read.
      // Only safe for new-format projects (taskIds in frontmatter, no embedded tasks).
      // For old-format projects we need the body anyway to migrate, so fall back to
      // a real read.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      const cacheUsable =
        cached && cached[FRONTMATTER_KEY] === true && !Array.isArray(cached.tasks) && Array.isArray(cached.taskIds)

      let frontmatter: Record<string, unknown> | null = null
      let body = ''
      let bodyRead = false
      if (cacheUsable) {
        frontmatter = cached
      } else {
        const content = await this.app.vault.cachedRead(file)
        const parsed = parseFrontmatter(content)
        frontmatter = parsed.frontmatter
        body = parsed.body
        bodyRead = true
      }
      if (!frontmatter || frontmatter[FRONTMATTER_KEY] !== true) return null

      const hasEmbeddedTasks = Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0

      const project = hydrateProjectFromFrontmatter(frontmatter, body, file.path, file.basename)
      if (bodyRead) this.hydratedBodies.add(project)

      if (hasEmbeddedTasks) {
        project.tasks = hydrateTasks((frontmatter.tasks as unknown[]) ?? [])
        rebuildTaskIndex(project)
        // Old format: no per-task files on disk yet, so mark everything dirty.
        this.markAllDirty(project, 'full')
      } else {
        const taskFolder = this.projectTaskFolder(project)
        const taskIds = Array.isArray(frontmatter.taskIds) ? (frontmatter.taskIds as string[]) : []
        project.tasks = await this.loadTasksFromFolder(taskFolder, taskIds)
        rebuildTaskIndex(project)
        // Memory matches disk now, drop any stale dirty entries.
        this.clearDirty(project)
      }

      this.projectCache.set(file.path, project)
      return project
    } catch (e) {
      console.error(`[PM] Failed to load project ${file.path}:`, e)
      new Notice(`Project Manager: Failed to load "${file.basename}". Check console for details.`)
      return null
    }
  }

  private async loadTasksFromFolder(folderPath: string, topLevelIds: string[]): Promise<Task[]> {
    const folder = this.app.vault.getAbstractFileByPath(folderPath)
    if (!(folder instanceof TFolder)) return []

    const taskMap = new Map<string, Task>()
    const subtaskIdsMap = new Map<string, string[]>()
    const parentIdMap = new Map<string, string>()
    const archivePrefix = normalizePath(folderPath + '/Archive') + '/'

    // Walk the task folder directly (plus Archive). Don't scan the whole vault.
    const files: TFile[] = []
    const collect = (f: TFolder): void => {
      for (const child of f.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
        else if (child instanceof TFolder) collect(child)
      }
    }
    collect(folder)

    const results = await Promise.all(files.map((file) => this.loadTaskFile(file)))
    for (let i = 0; i < files.length; i++) {
      const { task, subtaskIds, parentId } = results[i]
      if (task) {
        if (files[i].path.startsWith(archivePrefix)) {
          task.archived = true
        }
        taskMap.set(task.id, task)
        if (subtaskIds.length) subtaskIdsMap.set(task.id, subtaskIds)
        if (parentId) parentIdMap.set(task.id, parentId)
      }
    }

    for (const [taskId, sids] of subtaskIdsMap) {
      const task = taskMap.get(taskId)
      if (!task) continue
      task.subtasks = []
      for (const sid of sids) {
        const sub = taskMap.get(sid)
        if (sub) task.subtasks.push(sub)
      }
    }

    // Self-healing: re-parent orphaned tasks using parentId from their files
    const childIds = new Set<string>()
    for (const t of taskMap.values()) {
      for (const s of t.subtasks) childIds.add(s.id)
    }
    for (const [taskId, pid] of parentIdMap) {
      if (childIds.has(taskId)) continue // already parented
      const parent = taskMap.get(pid)
      if (!parent) continue
      const task = taskMap.get(taskId)
      if (!task) continue
      parent.subtasks.push(task)
      childIds.add(taskId)
      // Ensure parent's subtaskIds stay in sync
      if (!subtaskIdsMap.has(pid)) subtaskIdsMap.set(pid, [])
      const sids = subtaskIdsMap.get(pid)
      if (sids && !sids.includes(taskId)) sids.push(taskId)
      console.warn(
        `[PM] Self-healed orphan: re-parented task "${task.title}" (${taskId}) under "${parent.title}" (${pid})`
      )
    }

    const result: Task[] = []
    const pushed = new Set<string>()
    for (const id of topLevelIds) {
      if (pushed.has(id)) continue
      const task = taskMap.get(id)
      if (task) {
        result.push(task)
        pushed.add(id)
      }
    }
    for (const task of taskMap.values()) {
      if (pushed.has(task.id)) continue
      if (!childIds.has(task.id)) result.push(task)
    }

    return result
  }

  async loadTaskFile(file: TFile): Promise<{ task: Task | null; subtaskIds: string[]; parentId: string | null }> {
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the body
      // read. The description stays empty until loadTaskBody fills it on modal
      // open, or a 'full' save reads it back inline.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      if (cached && cached[TASK_FRONTMATTER_KEY] === true) {
        return hydrateTaskFromFile(cached, '', file.path)
      }

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || frontmatter[TASK_FRONTMATTER_KEY] !== true) {
        return { task: null, subtaskIds: [], parentId: null }
      }

      const result = hydrateTaskFromFile(frontmatter, body, file.path)
      this.hydratedBodies.add(result.task)
      return result
    } catch (e) {
      if (e instanceof Error && e.message.includes('ENOENT')) {
        console.warn(`[PM] Task file no longer exists, skipping: ${file.path}`)
      } else {
        console.error(`[PM] Failed to load task ${file.path}:`, e)
        new Notice(`Project Manager: Failed to load task "${file.basename}". Check console for details.`)
      }
      return { task: null, subtaskIds: [], parentId: null }
    }
  }

  /**
   * Read the task's file body and populate its description if not already
   * loaded. Modal callers use this to render the real description in one paint.
   * No-op for tasks whose description is already known to match disk.
   */
  async loadTaskBody(task: Task): Promise<void> {
    if (this.hydratedBodies.has(task)) return
    if (!task.filePath) {
      this.hydratedBodies.add(task)
      return
    }
    const file = this.app.vault.getAbstractFileByPath(task.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(task)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { body } = parseFrontmatter(content)
    task.description = stripAutoGeneratedContent(body)
    this.hydratedBodies.add(task)
  }

  /** Same as loadTaskBody but for the project file's body. */
  async loadProjectBody(project: Project): Promise<void> {
    if (this.hydratedBodies.has(project)) return
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(project)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { frontmatter, body } = parseFrontmatter(content)
    const fmDesc = frontmatter?.description
    project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
    this.hydratedBodies.add(project)
  }

  // ─── Save ──────────────────────────────────────────────────────────────────

  async saveProject(project: Project): Promise<void> {
    const key = project.filePath
    const prev = this.saveQueues.get(key) ?? Promise.resolve()
    const next = (async () => {
      await prev
      await this.doSaveProject(project)
    })()
    this.saveQueues.set(
      key,
      (async () => {
        try {
          await next
        } catch {
          // swallow so the next queued save still runs after a failure
        }
      })()
    )
    return next
  }

  private async doSaveProject(project: Project): Promise<void> {
    // Snapshot the dirty map and drop the live entry up front (before any await),
    // so concurrent markDirty calls land in the next save's map, not this one's.
    const dirty = this.dirtyTasks.get(project.filePath) ?? new Map<string, DirtyKind>()
    this.dirtyTasks.delete(project.filePath)

    try {
      project.updatedAt = new Date().toISOString()

      const taskFolder = this.projectTaskFolder(project)
      await this.ensureFolder(taskFolder)

      await this.saveDirtyTasks(project, taskFolder, dirty)

      const file = this.app.vault.getAbstractFileByPath(project.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(project.filePath)
        // Atomic read-modify-write. The mutator recovers the on-disk description
        // when the in-memory project hasn't been hydrated yet.
        await this.app.vault.process(file, (content) => {
          if (!this.hydratedBodies.has(project)) {
            const { frontmatter, body } = parseFrontmatter(content)
            const fmDesc = frontmatter?.description
            project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
          }
          return serializeProject(project, this.statusesFor(project))
        })
        this.hydratedBodies.add(project)
      } else {
        const content = serializeProject(project, this.statusesFor(project))
        this.markSelfWrite(project.filePath)
        await this.app.vault.create(project.filePath, content)
        this.hydratedBodies.add(project)
      }
      // The object we just saved is the canonical in-memory copy (it may be a
      // clone of a previously cached project, e.g. from the project modal).
      this.projectCache.set(project.filePath, project)
    } catch (e) {
      // Save failed. Merge the snapshot back so the next save retries.
      for (const [id, kind] of dirty) this.markDirty(project, [id], kind)
      if (e instanceof TaskFileNameConflictError) throw e
      console.error(`[PM] Failed to save project "${project.title}":`, e)
      new Notice(`Project Manager: Failed to save "${project.title}". Check console for details.`)
      throw e
    }
  }

  /**
   * Write exactly the dirty tasks, located through the O(1) task index instead
   * of walking the whole tree. Writes target distinct files, so they run
   * concurrently — batched.
   */
  private async saveDirtyTasks(project: Project, folder: string, dirty: Map<string, DirtyKind>): Promise<void> {
    // Safety net: a task that has never been written to disk must get a file
    // even if no mutator marked it.
    for (const [id, entry] of project.taskIndex) {
      if (!entry.task.filePath && !dirty.has(id)) dirty.set(id, 'full')
    }
    if (dirty.size === 0) return

    const jobs: { task: Task; parentTask: Task | null; folder: string; kind: DirtyKind }[] = []
    const targetPaths = new Set<string>()
    let hasArchived = false
    for (const [id, kind] of dirty) {
      const entry = project.taskIndex.get(id)
      if (!entry) continue // deleted after being marked dirty
      const { task, parentId } = entry
      const targetFolder = task.archived ? normalizePath(folder + '/Archive') : folder
      if (task.archived) hasArchived = true
      // Two dirty tasks resolving to the same file would race below and surface
      // as a generic create error; detect it up front and keep the typed error.
      const path = normalizePath(resolveTaskPath(task, targetFolder, task.filePath))
      if (targetPaths.has(path)) throw new TaskFileNameConflictError(path)
      targetPaths.add(path)
      jobs.push({ task, parentTask: parentId ? findTaskById(project, parentId) : null, folder: targetFolder, kind })
    }
    if (hasArchived) await this.ensureFolder(normalizePath(folder + '/Archive'))

    const errors: Error[] = []
    const batchSize = 16
    for (let i = 0; i < jobs.length; i += batchSize) {
      const results = await Promise.allSettled(
        jobs.slice(i, i + batchSize).map((j) => this.saveTaskFile(j.task, project, j.parentTask, j.folder, j.kind))
      )
      for (const r of results) {
        if (r.status === 'rejected') errors.push(r.reason instanceof Error ? r.reason : new Error(String(r.reason)))
      }
    }
    if (errors.length) {
      if (errors.length === 1 && errors[0] instanceof TaskFileNameConflictError) throw errors[0]
      throw new Error(`Failed to save ${errors.length} task(s): ${errors.map((e) => e.message).join('; ')}`)
    }
  }

  private async saveTaskFile(
    task: Task,
    project: Project,
    parentTask: Task | null,
    folder: string,
    kind: DirtyKind
  ): Promise<void> {
    const previousPath = task.filePath
    const filePath = normalizePath(resolveTaskPath(task, folder, previousPath))
    const renamed = previousPath !== undefined && previousPath !== filePath

    try {
      // Frontmatter-only fast path: leave the body alone entirely.
      if (kind === 'fm' && previousPath && !renamed) {
        const existing = this.app.vault.getAbstractFileByPath(filePath)
        if (existing instanceof TFile) {
          this.markSelfWrite(filePath)
          const next = buildTaskFrontmatter(task, project, parentTask)
          await this.app.fileManager.processFrontMatter(existing, (fm: Record<string, unknown>) => {
            for (const k of Object.keys(fm)) Reflect.deleteProperty(fm, k)
            Object.assign(fm, next)
          })
          return
        }
        // File missing somehow; fall through to recreate it.
      }

      const existing = this.app.vault.getAbstractFileByPath(filePath)
      if (existing instanceof TFile && existing.path !== previousPath) {
        throw new TaskFileNameConflictError(filePath)
      }

      if (existing instanceof TFile) {
        // In-place full rewrite, atomic. Recover description from disk when not hydrated.
        this.markSelfWrite(filePath)
        await this.app.vault.process(existing, (content) => {
          if (!this.hydratedBodies.has(task)) {
            task.description = stripAutoGeneratedContent(parseFrontmatter(content).body)
          }
          return serializeTask(task, project, parentTask, this.statusesFor(project))
        })
      } else {
        // New file or rename target. For a rename of an unhydrated task, read
        // the old file once to recover the description before creating the new one.
        if (!this.hydratedBodies.has(task) && previousPath) {
          const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
          if (oldFile instanceof TFile) {
            const content = await this.app.vault.cachedRead(oldFile)
            task.description = stripAutoGeneratedContent(parseFrontmatter(content).body)
          }
        }
        const content = serializeTask(task, project, parentTask, this.statusesFor(project))
        this.markSelfWrite(filePath)
        await this.app.vault.create(filePath, content)
      }
      task.filePath = filePath
      this.hydratedBodies.add(task)

      if (renamed && previousPath) {
        const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
        if (oldFile instanceof TFile) {
          this.markSelfWrite(previousPath)
          await this.app.fileManager.trashFile(oldFile)
        }
        // Keep the task's attachment folder with the renamed note.
        this.markSelfWrite(this.taskFolder(previousPath))
        this.markSelfWrite(this.taskFolder(filePath))
        await moveTaskAttachmentFolder(this.app, previousPath, filePath)
      }
    } catch (e) {
      if (!(e instanceof TaskFileNameConflictError)) {
        console.error(`[PM] Failed to save task "${task.title}" (${task.id}):`, e)
      }
      throw e
    }
  }

  /**
   * Pre-flight check: would saving this task (at its current title) collide
   * with another file already in the vault? Returns a typed error callers can
   * surface inline, or null if the save would proceed cleanly.
   */
  findTaskFileConflict(project: Project, task: Task): TaskFileNameConflictError | null {
    const baseFolder = this.projectTaskFolder(project)
    const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
    const desired = normalizePath(resolveTaskPath(task, folder, task.filePath))
    if (desired === task.filePath) return null
    const existing = this.app.vault.getAbstractFileByPath(desired)
    return existing instanceof TFile ? new TaskFileNameConflictError(desired) : null
  }

  // ─── CRUD shortcuts ────────────────────────────────────────────────────────

  async createProject(title: string, folder: string): Promise<Project> {
    const safeName = title.replace(/[\\/:*?"<>|]/g, '-')
    const filePath = normalizePath(`${folder}/${safeName}.md`)
    const project = makeProject(title, filePath)
    // Persist the caller-supplied directory as the project's `path` so discovery
    // and task resolution can honor it wherever the file lives (INT-014, R8/R10).
    project.path = folder
    await this.ensureFolder(this.projectTaskFolder(project))
    await this.saveProject(project)
    return project
  }

  async insertTask(project: Project, task: Task, parentId: string | null = null): Promise<void> {
    if (!task.completed && isTerminalStatus(task.status, this.statusesFor(project))) {
      task.completed = today().toString()
    }
    this.hydratedBodies.add(task)
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id], 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Ingest an externally-authored `pm-task` file that appeared under this
   * project's `<Name>_tasks/` folder (created or modified outside the plugin).
   *
   * Backfills a unique `id` (first) plus the full required frontmatter onto the
   * file via processFrontMatter — self-write-marked so the resulting modify
   * event is not re-ingested (no echo) — resolves blank fields to their
   * defaults, adds the task to the in-memory tree, and persists the project's
   * ordering (`taskIds`, or the parent's `subtaskIds` when parented). Returns
   * the ingested task, or null for a non-pm-task / malformed / out-of-folder
   * file; those never throw and leave the tree untouched.
   */
  async ingestExternalTask(project: Project, file: TFile): Promise<Task | null> {
    try {
      // Only files under this project's tasks folder are ingested (loose files
      // elsewhere in the vault are not — see INT-013 Non-Goals).
      const taskFolder = this.projectTaskFolder(project)
      const filePath = normalizePath(file.path)
      if (!filePath.startsWith(normalizePath(taskFolder) + '/')) return null

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || frontmatter[TASK_FRONTMATTER_KEY] !== true) return null

      // Backfill a unique id first: a blank/absent id gets a freshly minted one.
      const rawId = frontmatter.id
      const id = typeof rawId === 'string' && rawId.length > 0 ? rawId : makeId()

      // Idempotent: a task the store already tracks under this id is not
      // re-added. Recover its filePath if it was cache-loaded without one.
      const existing = findTaskById(project, id)
      if (existing) {
        if (!existing.filePath) existing.filePath = filePath
        return existing
      }

      // Blank status/priority resolve to defaults inside mapRawToTask.
      const { task, parentId } = hydrateTaskFromFile({ ...frontmatter, id }, body, filePath)
      task.id = id
      this.hydratedBodies.add(task)

      // Honor parentId only when the parent actually exists; otherwise top-level.
      const resolvedParentId = parentId && findTaskById(project, parentId) ? parentId : null

      // Archived state is derived from location, matching the folder load path.
      if (filePath.startsWith(normalizePath(taskFolder + '/Archive') + '/')) task.archived = true

      addTaskToTree(project.tasks, task, resolvedParentId)
      indexAddSubtree(project, task, resolvedParentId)

      // Backfill the full required frontmatter (id + defaults) back onto disk.
      // Self-mark first so the modify event this write raises is skipped.
      const parentTask = resolvedParentId ? findTaskById(project, resolvedParentId) : null
      const nextFm = buildTaskFrontmatter(task, project, parentTask)
      this.markSelfWrite(filePath)
      await this.app.fileManager.processFrontMatter(file, (fm: Record<string, unknown>) => {
        Object.assign(fm, nextFm)
      })

      // Persist ordering: a top-level id lands in the project file's taskIds;
      // a parented task's id lands in the parent's subtaskIds.
      if (resolvedParentId) this.markDirty(project, [resolvedParentId], 'full')
      await this.saveProject(project)

      return task
    } catch (e) {
      console.error(`[PM] Failed to ingest external task ${file.path}:`, e)
      return null
    }
  }

  /**
   * Route a vault create/modify of a possibly-external `pm-task` file to
   * ingestion. Finds the loaded project whose `<Name>_tasks/` folder holds the
   * file and hands off to `ingestExternalTask`; a file the store itself just
   * wrote (a self-write) is skipped so backfills don't echo. Non-task files and
   * files outside every loaded project's folder are ignored (returns null).
   *
   * This is the store-level seam the plugin's vault listeners call, so the
   * view/composition-root glue stays thin and testable.
   */
  async handleExternalTaskChange(file: TFile): Promise<Task | null> {
    // Non-destructive peek: the view's modify listener still needs the marker to
    // skip its own reload, so we must not consume it here.
    if (this.peekSelfWrite(normalizePath(file.path))) return null
    const path = normalizePath(file.path)
    for (const project of this.projectCache.values()) {
      const taskFolder = normalizePath(this.projectTaskFolder(project))
      if (path.startsWith(taskFolder + '/')) return this.ingestExternalTask(project, file)
    }
    return null
  }

  /**
   * Rename a loaded project through the plugin: rename its `Projects/<Name>.md`
   * file and its `<Name>_tasks` folder on disk (via the vault API), keep the
   * in-memory project + its tasks re-bound to the new paths, and persist the new
   * title (R13). Every path touched is `markSelfWrite`-marked inside one
   * suppression window so the vault rename events these writes raise are consumed
   * rather than echoed back into a second rename (R14).
   */
  async renameProject(project: Project, newTitle: string): Promise<void> {
    const oldPath = normalizePath(project.filePath)
    const parentDir = parentDirOf(oldPath)
    const safeName = newTitle.replace(/[\\/:*?"<>|]/g, '-')
    const newPath = normalizePath(parentDir ? `${parentDir}/${safeName}.md` : `${safeName}.md`)
    if (newPath === oldPath) {
      // Same on-disk name (title differs only cosmetically); just persist the title.
      project.title = newTitle
      await this.saveProject(project)
      return
    }
    if (this.app.vault.getAbstractFileByPath(newPath)) {
      throw new Error(`A note named "${safeName}" already exists.`)
    }

    const oldTaskFolder = normalizePath(oldPath.replace(/\.md$/, '_tasks'))
    const newTaskFolder = normalizePath(newPath.replace(/\.md$/, '_tasks'))
    // Self-mark every path we're about to touch, before any write, so the whole
    // rename lands inside one suppression window (R14 — no echo loop).
    this.markSelfWrite(oldPath)
    this.markSelfWrite(newPath)
    this.markSelfWrite(oldTaskFolder)
    this.markSelfWrite(newTaskFolder)

    const file = this.app.vault.getAbstractFileByPath(oldPath)
    if (file instanceof TFile) await this.app.fileManager.renameFile(file, newPath)
    await this.rebindRenamedProject(project, oldPath, newPath, oldTaskFolder, newTaskFolder, newTitle)
  }

  /**
   * Map an inbound vault `rename` event (old path → the renamed file) onto a
   * loaded item and update its name in memory + persisted title (R12). A
   * project-file rename cascades the `<Name>_tasks` folder rename and re-points
   * every task's `filePath`, so tasks stay attached (R15); a task-file rename
   * updates just that task. An event whose new path the store self-marked is the
   * echo of a plugin-initiated rename and is ignored; so is a rename whose old
   * path resolves to no loaded item.
   */
  async handleExternalRename(oldPath: string, file: TFile): Promise<void> {
    const normalizedOld = normalizePath(oldPath)
    const newPath = normalizePath(file.path)
    if (normalizedOld === newPath) return
    // A self-marked new path means our own renameProject raised this event.
    if (this.peekSelfWrite(newPath)) return

    const cachedProject = this.projectCache.get(normalizedOld)
    if (cachedProject) {
      const oldTaskFolder = normalizePath(normalizedOld.replace(/\.md$/, '_tasks'))
      const newTaskFolder = normalizePath(newPath.replace(/\.md$/, '_tasks'))
      await this.rebindRenamedProject(
        cachedProject,
        normalizedOld,
        newPath,
        oldTaskFolder,
        newTaskFolder,
        file.basename
      )
      return
    }
    // Otherwise it may be a task file renamed inside a loaded project's folder.
    await this.rebindRenamedTaskFile(normalizedOld, file)
  }

  /**
   * Shared rebind for a renamed project (used by both the outbound and inbound
   * paths). The project .md is assumed already at `newPath`; this cascades the
   * `<Name>_tasks` folder to follow the name, re-points each task's filePath,
   * moves the store's per-project bookkeeping to the new key, updates the
   * identity fields, and persists the new title (and `path` when the folder moved).
   */
  private async rebindRenamedProject(
    project: Project,
    oldPath: string,
    newPath: string,
    oldTaskFolder: string,
    newTaskFolder: string,
    newTitle: string
  ): Promise<void> {
    if (oldTaskFolder !== newTaskFolder) {
      const folder = this.app.vault.getAbstractFileByPath(oldTaskFolder)
      if (folder instanceof TFolder && !this.app.vault.getAbstractFileByPath(newTaskFolder)) {
        this.markSelfWrite(oldTaskFolder)
        this.markSelfWrite(newTaskFolder)
        await this.app.fileManager.renameFile(folder, newTaskFolder)
      }
      // Re-point every task's in-memory filePath under the new folder (R15).
      const oldPrefix = oldTaskFolder + '/'
      const newPrefix = newTaskFolder + '/'
      for (const { task } of flattenTasks(project.tasks)) {
        const fp = task.filePath ? normalizePath(task.filePath) : ''
        if (fp.startsWith(oldPrefix)) {
          const rebased = newPrefix + fp.slice(oldPrefix.length)
          this.markSelfWrite(fp)
          this.markSelfWrite(rebased)
          task.filePath = rebased
        }
      }
    }

    // Move per-project bookkeeping from the old key to the new one.
    const dirty = this.dirtyTasks.get(oldPath)
    this.dirtyTasks.delete(oldPath)
    const queue = this.saveQueues.get(oldPath)
    this.saveQueues.delete(oldPath)
    this.projectCache.delete(oldPath)

    project.title = newTitle
    project.filePath = newPath
    // Keep the declared `path` frontmatter aligned with the file's actual parent
    // folder when the item moved directories; a same-folder rename leaves it be.
    if (project.path !== undefined) project.path = parentDirOf(newPath)

    if (dirty) this.dirtyTasks.set(newPath, dirty)
    if (queue) this.saveQueues.set(newPath, queue)
    this.projectCache.set(newPath, project)

    await this.saveProject(project)
  }

  /** Rebind a single loaded task whose file was renamed in the vault (R12). */
  private async rebindRenamedTaskFile(oldPath: string, file: TFile): Promise<void> {
    const newPath = normalizePath(file.path)
    for (const project of this.projectCache.values()) {
      const taskFolder = normalizePath(this.projectTaskFolder(project))
      if (!oldPath.startsWith(taskFolder + '/')) continue
      const match = flattenTasks(project.tasks).find(
        (f) => f.task.filePath && normalizePath(f.task.filePath) === oldPath
      )
      if (!match) return
      const task = match.task
      task.filePath = newPath
      task.title = file.basename
      task.archived = newPath.startsWith(normalizePath(taskFolder + '/Archive') + '/')
      this.markSelfWrite(newPath)
      await this.app.fileManager.processFrontMatter(file, (fm: Record<string, unknown>) => {
        fm.title = task.title
      })
      return
    }
  }

  /**
   * Convert an arbitrary vault note into a top-level task file in the project's
   * tasks folder. The note body becomes the task description; notes that are
   * already pm-tasks are skipped. The task is picked up on the next project
   * load via the orphan self-heal, matching how the tasks folder is scanned.
   */
  async importNoteAsTask(project: Project, file: TFile, opts: ImportNoteOptions): Promise<'imported' | 'skipped'> {
    const content = await this.app.vault.read(file)
    const { frontmatter, body } = parseFrontmatter(content)
    if (frontmatter?.[TASK_FRONTMATTER_KEY] === true) return 'skipped'

    const task = makeTask({
      title: file.basename,
      description: body,
      status: opts.status,
      priority: opts.priority
    })
    const folder = this.projectTaskFolder(project)
    await this.ensureFolder(folder)
    const newFilePath = taskFilePath(task.title, folder)
    const newContent = serializeTask(task, project, null, this.statusesFor(project))

    if (opts.handling === 'move') {
      await this.app.fileManager.renameFile(file, newFilePath)
      const moved = this.app.vault.getAbstractFileByPath(newFilePath)
      if (moved instanceof TFile) {
        await this.app.vault.process(moved, () => newContent)
      }
    } else {
      await this.app.vault.create(newFilePath, newContent)
    }
    return 'imported'
  }

  /**
   * Persist a converted task forest (e.g. a TaskNotes import) as task files.
   * Each node's description comes from its source note body; 'move' turns the
   * source file into the task file, 'copy' leaves sources untouched. The
   * project file is not rewritten — the next load self-heals top-level order
   * and parenting from the written parentId/subtaskIds.
   */
  async importTaskForest(
    project: Project,
    roots: Task[],
    sources: Map<string, TFile>,
    handling: 'move' | 'copy'
  ): Promise<number> {
    const baseFolder = this.projectTaskFolder(project)
    await this.ensureFolder(baseFolder)
    let imported = 0

    const writeNode = async (task: Task, parent: Task | null): Promise<void> => {
      const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
      if (task.archived) await this.ensureFolder(folder)
      const source = sources.get(task.id)
      if (source) {
        const { body } = parseFrontmatter(await this.app.vault.read(source))
        task.description = body
      }
      const desired = taskFilePath(task.title, folder)
      const dest = this.uniqueChildPath(folder, desired.slice(desired.lastIndexOf('/') + 1))
      const content = serializeTask(task, project, parent, this.statusesFor(project))
      if (handling === 'move' && source) {
        await this.app.fileManager.renameFile(source, dest)
        const moved = this.app.vault.getAbstractFileByPath(dest)
        if (moved instanceof TFile) {
          await this.app.vault.process(moved, () => content)
        }
      } else {
        await this.app.vault.create(dest, content)
      }
      imported++
      for (const child of task.subtasks) {
        await writeNode(child, task)
      }
    }

    for (const root of roots) {
      await writeNode(root, null)
    }
    return imported
  }

  async duplicateTask(project: Project, sourceId: string, includeSubtasks: boolean): Promise<Task | null> {
    const source = findTaskById(project, sourceId)
    if (!source) return null
    const copy = cloneTaskSubtree(source, includeSubtasks)
    // Every task in a project shares one flat folder and its filename comes from
    // the title slug, so a clone that keeps the source title would write over the
    // original. Reserve a free "(copy)" title for the whole subtree, not just the
    // root, and across the clones we're about to add so siblings don't collide.
    const baseFolder = this.projectTaskFolder(project)
    const claimed = new Set<string>()
    const usedTitles = new Set(flattenTasks(project.tasks).map((f) => f.task.title))
    const claimName = (task: Task): void => {
      const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
      this.assignCopyName(task, folder, usedTitles, claimed)
    }
    // Clones don't have a filePath yet; their description in memory is whatever
    // came from the source. We need to write that body verbatim.
    claimName(copy)
    this.hydratedBodies.add(copy)
    for (const ft of flattenTasks(copy.subtasks)) {
      claimName(ft.task)
      this.hydratedBodies.add(ft.task)
    }
    const parentId = findParentId(project, sourceId)
    addTaskToTree(project.tasks, copy, parentId)
    moveTaskInTree(project.tasks, copy.id, sourceId, 'after')
    indexAddSubtree(project, copy, parentId)
    // Copy and every cloned descendant are new files.
    this.markSubtreeDirty(project, copy.id, 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
    return copy
  }

  private assignCopyName(task: Task, folder: string, usedTitles: Set<string>, claimed: Set<string>): void {
    const base = task.title.replace(/(?: \(copy(?: \d+)?\))+$/, '')
    for (let n = 1; ; n++) {
      const suffix = n === 1 ? ' (copy)' : ` (copy ${n})`
      const room = TASK_SLUG_MAX_LENGTH - suffix.length
      const title = (base.length > room ? base.slice(0, room).trimEnd() : base) + suffix
      const path = normalizePath(taskFilePath(title, folder))
      if (
        !usedTitles.has(title) &&
        !claimed.has(path) &&
        !(this.app.vault.getAbstractFileByPath(path) instanceof TFile)
      ) {
        usedTitles.add(title)
        claimed.add(path)
        task.title = title
        return
      }
    }
  }

  async moveTask(project: Project, taskId: string, newParentId: string | null): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    const oldParentId = findParentId(project, taskId)
    deleteTaskFromTree(project.tasks, taskId)
    addTaskToTree(project.tasks, task, newParentId)
    indexSetParent(project, taskId, newParentId)
    // Moved task's parentId is in frontmatter but its body's Parent: link also changes.
    this.markDirty(project, [taskId], 'full')
    // Old and new parents' bodies (Subtasks list) change.
    if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  async moveTasks(project: Project, taskIds: string[], newParentId: string | null): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const oldParentId = findParentId(project, id)
      deleteTaskFromTree(project.tasks, id)
      addTaskToTree(project.tasks, task, newParentId)
      indexSetParent(project, id, newParentId)
      this.markDirty(project, [id], 'full')
      if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    }
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Stamp or clear `completed` based on a status transition. Mutates `patch` so the
   * date lands in the same save as the status change. A patch that changes
   * `completed` away from the task's current value (a manual edit in the modal, or
   * an import) wins and is left untouched; otherwise crossing the
   * complete/incomplete boundary stamps today's date or clears it.
   *
   * The modal saves the whole task as the patch, so `patch.completed` is almost
   * always present and equal to the stored value — comparing against the task,
   * not just checking presence, is what lets auto-stamping fire from the modal.
   */
  private stampCompletion(project: Project, task: Task, patch: Partial<Task>): void {
    if (patch.status === undefined) return
    if (patch.completed !== undefined && patch.completed !== task.completed) return
    const statuses = this.statusesFor(project)
    const wasComplete = isTerminalStatus(task.status, statuses)
    const nowComplete = isTerminalStatus(patch.status, statuses)
    if (nowComplete && !wasComplete) patch.completed = today().toString()
    else if (!nowComplete && wasComplete) patch.completed = ''
  }

  async updateTask(project: Project, taskId: string, patch: Partial<Task>): Promise<void> {
    const task = findTaskById(project, taskId)
    const oldTitle = task?.title
    if (task) this.stampCompletion(project, task, patch)
    // The task editor saves the whole task, so a patch can add, rename, remove,
    // or reorder subtasks. Snapshot the pre-edit subtree to diff against once the
    // tree has the new one.
    const oldSubtree = task && patch.subtasks !== undefined ? flattenTasks(task.subtasks).map((f) => f.task) : []
    updateTaskInTree(project.tasks, taskId, patch)
    const titleChanged = task && patch.title !== undefined && patch.title !== oldTitle
    // Title change renames the file, which forces the rename branch in saveTaskFile
    // (body rewrite). Description/archived/subtasks patches require a body rewrite too.
    const kind: DirtyKind = patchNeedsBodyRewrite(patch) || titleChanged ? 'full' : 'fm'
    this.markDirty(project, [taskId], kind)
    // Patch-set description is the caller's intent; trust it as the new body.
    if (task && patch.description !== undefined) this.hydratedBodies.add(task)
    if (task && patch.subtasks !== undefined) {
      // Re-index the saved subtree and create/rename/trash the affected subtask
      // files; this also covers the children's Parent-link rewrite on a rename.
      await this.reconcileSubtasks(project, task, oldSubtree)
    } else if (task && titleChanged) {
      // Title change renames the file, which breaks direct children's Parent link.
      for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
    }
    await this.saveProject(project)
  }

  /**
   * After a save that carries a task's whole subtree (the task editor works on a
   * deep clone), make the index and the on-disk files match it: re-point the
   * index at the saved subtree objects, mark new/renamed/restatused subtasks for
   * a write, and trash the files of subtasks removed in the editor. Unchanged
   * subtasks aren't rewritten.
   */
  private async reconcileSubtasks(project: Project, parent: Task, oldSubtree: Task[]): Promise<void> {
    indexAddSubtree(project, parent, findParentId(project, parent.id))

    const old = new Map(oldSubtree.map((t) => [t.id, t]))
    const liveIds = new Set<string>()
    for (const { task } of flattenTasks(parent.subtasks)) {
      liveIds.add(task.id)
      const prev = old.get(task.id)
      if (!prev) {
        // Brand-new subtask: it needs its own file, body included.
        this.hydratedBodies.add(task)
        this.markDirty(project, [task.id], 'full')
      } else if (prev.title !== task.title) {
        this.markDirty(project, [task.id], 'full')
      } else if (prev.status !== task.status || prev.completed !== task.completed || prev.progress !== task.progress) {
        this.markDirty(project, [task.id], 'fm')
      }
    }

    const folder = this.projectTaskFolder(project)
    for (const removed of oldSubtree) {
      if (liveIds.has(removed.id)) continue
      project.taskIndex.delete(removed.id)
      // The flat snapshot already lists every descendant, so trash this file only.
      if (removed.filePath) await this.deleteTaskFiles({ ...removed, subtasks: [] }, folder)
    }
  }

  /**
   * Apply a patch to several tasks in one save. `patch` may be a function
   * producing a per-task patch; return null to leave that task untouched.
   */
  async updateTasks(
    project: Project,
    taskIds: string[],
    patch: Partial<Task> | ((task: Task) => Partial<Task> | null)
  ): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const raw = typeof patch === 'function' ? patch(task) : patch
      if (!raw) continue
      // Copy a shared patch object before stamping so one task's completion date
      // doesn't bleed onto the next iteration through the same reference.
      const p = { ...raw }
      this.stampCompletion(project, task, p)
      const oldTitle = task.title
      updateTaskInTree(project.tasks, id, p)
      const titleChanged = p.title !== undefined && p.title !== oldTitle
      const kind: DirtyKind = patchNeedsBodyRewrite(p) || titleChanged ? 'full' : 'fm'
      this.markDirty(project, [id], kind)
      if (p.description !== undefined) this.hydratedBodies.add(task)
      if (titleChanged) {
        for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
      }
    }
    await this.saveProject(project)
  }

  /**
   * Move a task before/after a sibling. Sibling order persists in the parent's
   * subtaskIds (or the project file's taskIds for top-level tasks), so only the
   * parent needs a rewrite.
   */
  async reorderTask(project: Project, taskId: string, targetId: string, position: 'before' | 'after'): Promise<void> {
    if (!moveTaskInTree(project.tasks, taskId, targetId, position)) return
    const parentId = findParentId(project, targetId)
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  async deleteTasks(project: Project, taskIds: string[]): Promise<void> {
    const folder = this.projectTaskFolder(project)
    const dirtyParents = new Set<string>()
    for (const id of taskIds) {
      const parentId = findParentId(project, id)
      if (parentId) dirtyParents.add(parentId)
      const task = findTaskById(project, id)
      if (task) {
        await this.deleteTaskFiles(task, folder)
        indexRemoveSubtree(project, task)
      }
      deleteTaskFromTree(project.tasks, id)
    }
    // Parents' bodies (Subtasks list) shrink.
    if (dirtyParents.size) this.markDirty(project, dirtyParents, 'full')
    await this.saveProject(project)
  }

  async archiveTask(project: Project, taskId: string): Promise<void> {
    await doArchiveTask(this.app, project, taskId)
  }

  async unarchiveTask(project: Project, taskId: string): Promise<void> {
    await doUnarchiveTask(this.app, project, taskId)
  }

  async deleteTask(project: Project, taskId: string): Promise<void> {
    const parentId = findParentId(project, taskId)
    const task = findTaskById(project, taskId)
    if (task) {
      await this.deleteTaskFiles(task, this.projectTaskFolder(project))
      indexRemoveSubtree(project, task)
    }
    deleteTaskFromTree(project.tasks, taskId)
    // Parent's Subtasks list shrinks.
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  private async deleteTaskFiles(task: Task, folder: string): Promise<void> {
    for (const sub of task.subtasks) {
      await this.deleteTaskFiles(sub, folder)
    }
    if (task.filePath) {
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(task.filePath)
        await this.app.fileManager.trashFile(file)
      }
      // Trash the task's own folder (its attachments) alongside the note.
      const taskDir = this.app.vault.getAbstractFileByPath(this.taskFolder(task.filePath))
      if (taskDir instanceof TFolder) {
        await this.deleteFolderRecursive(taskDir)
      }
    }
  }

  /** A task's own folder, holding its attachments: the task file path minus `.md`. */
  private taskFolder(taskFilePath: string): string {
    return taskFilePath.replace(/\.md$/, '')
  }

  /**
   * Save a pasted or dropped file under the task's own `attachments` folder,
   * keeping it with the task instead of Obsidian's vault-wide default attachment
   * location. Returns the created file so the caller can embed it.
   */
  async saveTaskAttachment(project: Project, task: Task, fileName: string, data: ArrayBuffer): Promise<TFile> {
    const taskPath = task.filePath ?? taskFilePath(task.title, this.projectTaskFolder(project))
    const dir = normalizePath(`${this.taskFolder(taskPath)}/attachments`)
    this.markSelfWrite(this.taskFolder(taskPath))
    this.markSelfWrite(dir)
    await this.ensureFolder(dir)
    const path = this.uniqueChildPath(dir, fileName)
    this.markSelfWrite(path)
    return this.app.vault.createBinary(path, data)
  }

  private uniqueChildPath(folder: string, fileName: string): string {
    const dot = fileName.lastIndexOf('.')
    const base = dot > 0 ? fileName.slice(0, dot) : fileName
    const ext = dot > 0 ? fileName.slice(dot) : ''
    let candidate = normalizePath(`${folder}/${base}${ext}`)
    for (let n = 1; this.app.vault.getAbstractFileByPath(candidate); n++) {
      candidate = normalizePath(`${folder}/${base} ${n}${ext}`)
    }
    return candidate
  }

  async deleteProject(project: Project): Promise<void> {
    const taskFolder = this.projectTaskFolder(project)
    const folder = this.app.vault.getAbstractFileByPath(taskFolder)
    if (folder instanceof TFolder) {
      await this.deleteFolderRecursive(folder)
    }
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (file instanceof TFile) {
      this.markSelfWrite(project.filePath)
      await this.app.fileManager.trashFile(file)
    }
    this.clearDirty(project)
    this.saveQueues.delete(project.filePath)
    this.projectCache.delete(project.filePath)
  }

  private async deleteFolderRecursive(folder: TFolder): Promise<void> {
    for (const child of folder.children.slice()) {
      if (child instanceof TFile) {
        this.markSelfWrite(child.path)
        await this.app.fileManager.trashFile(child)
      } else if (child instanceof TFolder) {
        await this.deleteFolderRecursive(child)
      }
    }
    await this.app.fileManager.trashFile(folder)
  }

  // ─── Scheduling ──────────────────────────────────────────────────────────

  /**
   * Run dependency-based scheduling on the project. Applies computed date
   * patches and saves; returns the number of tasks that were adjusted.
   * A no-op when auto-scheduling is off for this project, so callers can
   * invoke it unconditionally after a change.
   */
  async scheduleAfterChange(project: Project, changedTaskId?: string): Promise<number> {
    const config = this.configFor(project)
    if (!config.autoSchedule) return 0
    const { patches } = computeSchedule(project.tasks, changedTaskId, config.statuses)
    if (patches.length === 0) return 0

    for (const p of patches) {
      updateTaskInTree(project.tasks, p.taskId, { start: p.start, due: p.due })
      // Dates live in frontmatter only.
      this.markDirty(project, [p.taskId], 'fm')
    }
    await this.saveProject(project)
    return patches.length
  }
}
