import type { Plugin, TAbstractFile } from 'obsidian'
import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import type { PMSettings, Project, ResolvedProjectConfig, StatusConfig, Task } from '../types'
import { DEFAULT_SETTINGS, makeProject, makeTask } from '../types'
import { today } from '../dates'
import { isTerminalStatus } from '../utils'
import { archiveTask as doArchiveTask, unarchiveTask as doUnarchiveTask } from './ArchiveOps'
import { resolveProjectConfig } from './ProjectConfig'
import { computeSchedule } from './Scheduler'
import {
  findParentId,
  findTaskById,
  indexAddSubtree,
  indexRemoveSubtree,
  indexSetParent,
  rebuildTaskIndex
} from './TaskIndex'
import {
  addTaskToTree,
  cloneTaskSubtree,
  deleteTaskFromTree,
  flattenTasks,
  moveTaskInTree,
  updateTaskInTree
} from './TaskTreeOps'
import {
  getTaskNotesConfig,
  isSharedTaskNote,
  parseBlockedBy,
  reconcileDependencies,
  reconcileSharedField,
  resolveBlockedByUid,
  resolveProjectLinks,
  resolveTaskNotesRef,
  TASKNOTES_SHARED_FIELDS,
  type TaskNotesConfig
} from '../integrations/tasknotes'
import { collectForeign, hydrateProjectFromFrontmatter, hydrateTaskFromFile, hydrateTasks } from './YamlHydrator'
import { FRONTMATTER_KEY, TASK_FRONTMATTER_KEY, parseFrontmatter, stripAutoGeneratedContent } from './YamlParser'
import {
  buildTaskFrontmatter,
  noteBasename,
  serializeProject,
  serializeTask,
  taskFilePath,
  TASK_SLUG_MAX_LENGTH
} from './YamlSerializer'
import { ensureFolder, moveTaskAttachmentFolder } from './vaultFs'
import type { ImportNoteOptions, TaskSource } from './TaskSource'

/**
 * 'fm' — only frontmatter changed; body content is unaffected. Save path can
 * use processFrontMatter and skip reading the body.
 * 'full' — body content depends on the change (description edited, file
 * renamed, archived flag flipped, structural relationships moved). Save path
 * rewrites the whole file atomically via vault.process.
 */
type DirtyKind = 'fm' | 'full'

/** Patches that touch any of these require rewriting the body, not just the frontmatter. */
function patchNeedsBodyRewrite(patch: Partial<Task>): boolean {
  // `subtasks` changes the parent's `## Subtasks` list, which lives in the body.
  return patch.description !== undefined || patch.archived !== undefined || patch.subtasks !== undefined
}

/** A basename of this exact length that prefixes the title's slug is kept as-is. */
const LEGACY_SLUG_CAP = 40

/**
 * Pick a save path. New tasks get the bare slug; an existing file is left where
 * it is when its name still matches the title, so an unchanged title isn't renamed.
 */
function resolveTaskPath(task: Task, folder: string, previousPath: string | undefined): string {
  const desired = taskFilePath(task.title, folder)
  if (!previousPath) return desired
  // A cross-folder TaskNotes note (Phase 3b) is a file we don't own the location
  // of: keep it exactly where it is, even on a title change (its title lives in
  // frontmatter, not the filename). We still rewrite its frontmatter in place.
  if (task.external) return previousPath
  const desiredBasename = desired.slice(desired.lastIndexOf('/') + 1).replace(/\.md$/, '')
  const previousFolder = previousPath.slice(0, previousPath.lastIndexOf('/'))
  const previousBasename = previousPath.slice(previousPath.lastIndexOf('/') + 1).replace(/\.md$/, '')
  if (previousFolder !== folder) return desired
  const legacyBasename = `${desiredBasename}-${task.id.slice(0, 8)}`
  if (previousBasename === legacyBasename) return previousPath
  if (previousBasename.length === LEGACY_SLUG_CAP && previousBasename === desiredBasename.slice(0, LEGACY_SLUG_CAP)) {
    return previousPath
  }
  return desired
}

/** Thrown when saving a task would collide with an existing file in the vault. */
export class TaskFileNameConflictError extends Error {
  constructor(public readonly path: string) {
    super(`A note named "${fileNameFromPath(path)}" already exists.`)
    this.name = 'TaskFileNameConflictError'
  }

  get fileName(): string {
    return fileNameFromPath(this.path)
  }
}

function fileNameFromPath(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.md$/, '')
}

/**
 * Handles all read/write operations against the Obsidian vault.
 *
 * Storage layout:
 *   Projects/<ProjectName>.md         — project metadata (no task data)
 *   Projects/<ProjectName>/<slug>.md  — one .md per task
 *
 * The in-memory Project.tasks tree is assembled on load from individual
 * task files and remains unchanged for views.
 */
export class ProjectStore implements TaskSource {
  /** Per-project promise chains to serialize concurrent saves */
  private saveQueues = new Map<string, Promise<void>>()

  /**
   * Task IDs whose .md file needs writing on the next save, with the kind of
   * write required ('fm' for frontmatter-only, 'full' for whole-file rewrite).
   * Tasks with no filePath are always written as 'full'.
   */
  private dirtyTasks = new Map<string, Map<string, DirtyKind>>()

  /**
   * Tasks and projects whose in-memory `description` is known to match disk
   * (either we just wrote it, or we loaded it from the body). Cache-loaded
   * objects start out absent — their description is empty until loadTaskBody /
   * loadProjectBody fills it, or until a 'full' save reads it back inline.
   */
  private hydratedBodies = new WeakSet<Task | Project>()

  /**
   * Projects already loaded this session, keyed by file path. The cached
   * object is the in-memory canonical copy: mutators keep it current, every
   * successful save re-points the entry at the saved object, and external
   * (non-self-write) vault events drop the entry so the next load re-reads.
   */
  private projectCache = new Map<string, Project>()

  /**
   * Reverse index for cross-folder TaskNotes ingestion (Phase 3b). Maps a
   * project file path → the external shared task notes whose `projects[]`
   * wikilink resolves to it and that live *outside* that project's `_tasks/`
   * folder. `null` = not built yet (or invalidated); rebuilt lazily by
   * `ensureExternalIndex` on the next project load. Empty when interop is off.
   */
  private externalTaskIndex: Map<string, Set<string>> | null = null

  /**
   * Companion to `externalTaskIndex`: external note path → the project paths it
   * links to. Lets a vault change to an external note invalidate exactly the
   * projects that reference it, without re-sweeping.
   */
  private externalTaskOwners = new Map<string, Set<string>>()

  /**
   * Paths we've just written, created, or trashed ourselves, timestamped.
   * The view's modify/delete listeners consume markers to skip reloads; the
   * cache invalidation listeners peek at them without consuming.
   * Stale entries (older than the window) are treated as never-marked.
   */
  private selfWrites = new Map<string, number>()
  private static readonly SELF_WRITE_WINDOW_MS = 5000

  constructor(
    private app: App,
    private getSettings: () => PMSettings = () => DEFAULT_SETTINGS
  ) {}

  configFor(project: Project): ResolvedProjectConfig {
    return resolveProjectConfig(project, this.getSettings())
  }

  private statusesFor(project: Project): StatusConfig[] {
    return this.configFor(project).statuses
  }

  /**
   * TaskNotes' task-identification config when interop is on and TaskNotes is
   * installed, else null. Drives the dual identifier on write and which foreign
   * notes we accept on read.
   */
  private taskNotesConfig(): TaskNotesConfig | null {
    if (!this.getSettings().taskNotesInterop) return null
    return getTaskNotesConfig(this.app)
  }

  /**
   * Whether to adopt TaskNotes' time shape (`timeEntries` + minute estimates) as
   * canonical on read/write. Requires interop on — the toggle is meaningless when
   * the plugins are kept separate. Drives the `timeSync` flag into hydrate/serialize.
   */
  private timeSyncEnabled(): boolean {
    return this.getSettings().taskNotesInterop && this.getSettings().taskNotesTimeSync
  }

  /**
   * Whether a scanned note counts as a PM task: it carries our `pm-task` marker,
   * or (with interop on) TaskNotes' identifier plus a project association. A file
   * with both markers is one task — it's read once, from its single file.
   */
  private isTaskFile(fm: Record<string, unknown>, tnConfig: TaskNotesConfig | null): boolean {
    if (fm[TASK_FRONTMATTER_KEY] === true) return true
    return tnConfig !== null && isSharedTaskNote(fm, tnConfig)
  }

  // ─── Dirty tracking ───────────────────────────────────────────────────────

  private markDirty(project: Project, taskIds: Iterable<string>, kind: DirtyKind): void {
    let map = this.dirtyTasks.get(project.filePath)
    if (!map) {
      map = new Map()
      this.dirtyTasks.set(project.filePath, map)
    }
    for (const id of taskIds) {
      // Upgrade-only: 'full' wins over 'fm', never the reverse.
      if (map.get(id) === 'full') continue
      map.set(id, kind)
    }
  }

  private markSubtreeDirty(project: Project, taskId: string, kind: DirtyKind): void {
    const task = findTaskById(project, taskId)
    if (!task) return
    this.markDirty(project, [taskId], kind)
    for (const ft of flattenTasks(task.subtasks)) {
      this.markDirty(project, [ft.task.id], kind)
    }
  }

  private markAllDirty(project: Project, kind: DirtyKind): void {
    const ids: string[] = []
    for (const ft of flattenTasks(project.tasks)) ids.push(ft.task.id)
    this.markDirty(project, ids, kind)
  }

  private clearDirty(project: Project): void {
    this.dirtyTasks.delete(project.filePath)
  }

  // ─── Self-write tracking ──────────────────────────────────────────────────

  private markSelfWrite(path: string): void {
    // Created files have no consumer, so sweep expired markers before they pile up.
    if (this.selfWrites.size > 256) {
      const cutoff = Date.now() - ProjectStore.SELF_WRITE_WINDOW_MS
      for (const [p, t] of this.selfWrites) {
        if (t < cutoff) this.selfWrites.delete(p)
      }
    }
    this.selfWrites.set(path, Date.now())
  }

  /** Returns true if we wrote this path recently. Consumes the marker either way. */
  consumeSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    if (ts === undefined) return false
    this.selfWrites.delete(path)
    return Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /** Like consumeSelfWrite, but non-destructive — view listeners still need the marker. */
  private peekSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    return ts !== undefined && Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /**
   * Wire vault events that drop cached projects on external changes. Call once
   * from onload, before any view registers listeners — these must run first so
   * a view's reload after an external edit misses the stale cache entry.
   */
  registerCacheInvalidation(plugin: Plugin): void {
    const onChange = (file: TAbstractFile): void => this.invalidateForPath(file.path)
    plugin.registerEvent(this.app.vault.on('create', onChange))
    plugin.registerEvent(this.app.vault.on('modify', onChange))
    plugin.registerEvent(this.app.vault.on('delete', onChange))
    plugin.registerEvent(
      this.app.vault.on('rename', (file, oldPath) => {
        this.invalidateForPath(file.path)
        this.invalidateForPath(oldPath)
      })
    )
    // A vault create/modify fires *before* Obsidian re-parses the file's
    // frontmatter, so `invalidateForPath` reading `metadataCache` there sees a
    // stale (often empty) cache — a note that just gained a TaskNotes `projects[]`
    // link wouldn't bust the cross-folder index and would stay invisible until a
    // reload. `metadata.changed` fires *after* the parse, so re-invalidate here to
    // catch the now-visible link.
    plugin.registerEvent(this.app.metadataCache.on('changed', (file) => this.invalidateForPath(file.path)))
  }

  private invalidateForPath(path: string): void {
    if (this.peekSelfWrite(path)) return

    // Phase 3b: a change to a cross-folder shared note busts the projects it
    // links to — both the ones it *used* to link (from the index) and the ones
    // it links *now* (it may have just gained/changed a `projects[]` entry) —
    // and drops the index so the next load re-sweeps. Not gated on projectCache
    // size: the index must go stale even when nothing is currently cached.
    const previousOwners = this.externalTaskOwners.get(path)
    const currentLinks = this.externalLinksForFile(path, this.taskNotesConfig())
    if (previousOwners || currentLinks.length > 0) {
      for (const p of previousOwners ?? []) this.projectCache.delete(p)
      for (const p of currentLinks) this.projectCache.delete(p)
      this.externalTaskIndex = null
    }

    // A project file itself changing (create/rename/delete) shifts the index's
    // keys (which are project paths) — drop it so they're recomputed on reload.
    const projectsFolder = normalizePath(this.getSettings().projectsFolder)
    if (path.endsWith('.md') && path.slice(0, path.lastIndexOf('/')) === projectsFolder) {
      this.externalTaskIndex = null
    }

    if (this.projectCache.size === 0) return
    for (const key of this.projectCache.keys()) {
      if (path === key || path.startsWith(key.replace(/\.md$/, '_tasks') + '/')) {
        this.projectCache.delete(key)
      }
    }
  }

  // ─── Folder helpers ────────────────────────────────────────────────────────

  async ensureFolder(folderPath: string): Promise<void> {
    await ensureFolder(this.app, folderPath)
  }

  /** Get the task subfolder path for a project */
  private projectTaskFolder(project: Project): string {
    return project.filePath.replace(/\.md$/, '_tasks')
  }

  // ─── Cross-folder external-task index (Phase 3b) ───────────────────────────

  /**
   * Build the external-task index if it's stale. One sweep over the vault's
   * markdown files: a note that is a shared TaskNotes task and lives *outside* a
   * linked project's `_tasks/` folder is filed under each project its
   * `projects[]` resolves to. Cheap no-op when interop is off — no shared notes
   * exist, so both maps stay empty. Built once, reused across a load cycle, and
   * dropped by `invalidateForPath` when a relevant note changes.
   */
  private ensureExternalIndex(): void {
    if (this.externalTaskIndex) return
    const index = new Map<string, Set<string>>()
    this.externalTaskOwners.clear()
    const tnConfig = this.taskNotesConfig()
    if (!tnConfig) {
      this.externalTaskIndex = index
      return
    }
    for (const file of this.app.vault.getMarkdownFiles()) {
      for (const projectPath of this.externalLinksForFile(file.path, tnConfig)) {
        let linked = index.get(projectPath)
        if (!linked) {
          linked = new Set()
          index.set(projectPath, linked)
        }
        linked.add(file.path)
        let owners = this.externalTaskOwners.get(file.path)
        if (!owners) {
          owners = new Set()
          this.externalTaskOwners.set(file.path, owners)
        }
        owners.add(projectPath)
      }
    }
    this.externalTaskIndex = index
  }

  /**
   * The projects a note is a *cross-folder* shared task for: it carries
   * TaskNotes' marker, resolves via `projects[]`, and lives outside the target
   * project's own `_tasks/` folder (in-folder notes load via the folder walk).
   * Empty unless interop is on. Reused by index build and invalidation so both
   * apply the same folder-exclusion rule.
   */
  private externalLinksForFile(path: string, tnConfig: TaskNotesConfig | null): string[] {
    if (!tnConfig) return []
    const file = this.app.vault.getAbstractFileByPath(path)
    if (!(file instanceof TFile)) return []
    const fm = this.app.metadataCache.getFileCache(file)?.frontmatter
    if (!fm || !isSharedTaskNote(fm, tnConfig)) return []
    return resolveProjectLinks(fm, this.app, path).filter((p) => !path.startsWith(p.replace(/\.md$/, '_tasks') + '/'))
  }

  /** External shared task files linked to this project, resolved to TFiles. */
  private externalFilesFor(projectPath: string): TFile[] {
    this.ensureExternalIndex()
    const paths = this.externalTaskIndex?.get(projectPath)
    if (!paths) return []
    const files: TFile[] = []
    for (const p of paths) {
      const f = this.app.vault.getAbstractFileByPath(p)
      if (f instanceof TFile) files.push(f)
    }
    return files
  }

  // ─── Load ──────────────────────────────────────────────────────────────────

  async loadAllProjects(folder: string): Promise<Project[]> {
    await this.ensureFolder(folder)
    // Walk the projects folder directly. Don't scan the whole vault.
    const folderObj = this.app.vault.getAbstractFileByPath(folder)
    const files: TFile[] = []
    if (folderObj instanceof TFolder) {
      for (const child of folderObj.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
      }
    }
    const loaded = await Promise.all(files.map((f) => this.loadProject(f)))
    const projects = loaded.filter((p): p is Project => p !== null)
    return projects.sort((a, b) => a.title.localeCompare(b.title))
  }

  async loadProject(file: TFile): Promise<Project | null> {
    const cachedProject = this.projectCache.get(file.path)
    if (cachedProject) return cachedProject
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the disk read.
      // Only safe for new-format projects (taskIds in frontmatter, no embedded tasks).
      // For old-format projects we need the body anyway to migrate, so fall back to
      // a real read.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      const cacheUsable =
        cached && cached[FRONTMATTER_KEY] === true && !Array.isArray(cached.tasks) && Array.isArray(cached.taskIds)

      let frontmatter: Record<string, unknown> | null = null
      let body = ''
      let bodyRead = false
      if (cacheUsable) {
        frontmatter = cached
      } else {
        const content = await this.app.vault.cachedRead(file)
        const parsed = parseFrontmatter(content)
        frontmatter = parsed.frontmatter
        body = parsed.body
        bodyRead = true
      }
      if (!frontmatter || frontmatter[FRONTMATTER_KEY] !== true) return null

      const hasEmbeddedTasks = Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0

      const project = hydrateProjectFromFrontmatter(frontmatter, body, file.path, file.basename)
      if (bodyRead) this.hydratedBodies.add(project)

      if (hasEmbeddedTasks) {
        project.tasks = hydrateTasks((frontmatter.tasks as unknown[]) ?? [])
        rebuildTaskIndex(project)
        // Old format: no per-task files on disk yet, so mark everything dirty.
        this.markAllDirty(project, 'full')
      } else {
        const taskFolder = this.projectTaskFolder(project)
        const taskIds = Array.isArray(frontmatter.taskIds) ? (frontmatter.taskIds as string[]) : []
        const externalFiles = this.externalFilesFor(file.path)
        project.tasks = await this.loadTasksFromFolder(taskFolder, taskIds, externalFiles)
        rebuildTaskIndex(project)
        // Memory matches disk now, drop any stale dirty entries.
        this.clearDirty(project)
      }

      this.projectCache.set(file.path, project)
      return project
    } catch (e) {
      console.error(`[PM] Failed to load project ${file.path}:`, e)
      new Notice(`Project Manager: Failed to load "${file.basename}". Check console for details.`)
      return null
    }
  }

  private async loadTasksFromFolder(
    folderPath: string,
    topLevelIds: string[],
    externalFiles: TFile[] = []
  ): Promise<Task[]> {
    const folder = this.app.vault.getAbstractFileByPath(folderPath)
    // The folder may be missing yet still have cross-folder tasks linked via
    // `projects[]` (Phase 3b) — only bail when there's nothing to load at all.
    if (!(folder instanceof TFolder) && externalFiles.length === 0) return []

    const taskMap = new Map<string, Task>()
    const subtaskIdsMap = new Map<string, string[]>()
    const parentIdMap = new Map<string, string>()
    const archivePrefix = normalizePath(folderPath + '/Archive') + '/'

    // Walk the task folder directly (plus Archive). Don't scan the whole vault.
    const files: TFile[] = []
    const collect = (f: TFolder): void => {
      for (const child of f.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
        else if (child instanceof TFolder) collect(child)
      }
    }
    if (folder instanceof TFolder) collect(folder)
    // External shared notes join the same taskMap so the subtask/parent tree can
    // cross the folder boundary. They're never archived (archivePrefix can't match).
    const folderCount = files.length
    files.push(...externalFiles)

    const results = await Promise.all(files.map((file, i) => this.loadTaskFile(file, i >= folderCount)))
    for (let i = 0; i < files.length; i++) {
      const { task, subtaskIds, parentId } = results[i]
      if (task) {
        if (files[i].path.startsWith(archivePrefix)) {
          task.archived = true
        }
        taskMap.set(task.id, task)
        if (subtaskIds.length) subtaskIdsMap.set(task.id, subtaskIds)
        if (parentId) parentIdMap.set(task.id, parentId)
      }
    }

    this.resolveTaskNotesDependencies(taskMap)

    for (const [taskId, sids] of subtaskIdsMap) {
      const task = taskMap.get(taskId)
      if (!task) continue
      task.subtasks = []
      for (const sid of sids) {
        const sub = taskMap.get(sid)
        if (sub) task.subtasks.push(sub)
      }
    }

    // Self-healing: re-parent orphaned tasks using parentId from their files
    const childIds = new Set<string>()
    for (const t of taskMap.values()) {
      for (const s of t.subtasks) childIds.add(s.id)
    }
    for (const [taskId, pid] of parentIdMap) {
      if (childIds.has(taskId)) continue // already parented
      const parent = taskMap.get(pid)
      if (!parent) continue
      const task = taskMap.get(taskId)
      if (!task) continue
      parent.subtasks.push(task)
      childIds.add(taskId)
      // Ensure parent's subtaskIds stay in sync
      if (!subtaskIdsMap.has(pid)) subtaskIdsMap.set(pid, [])
      const sids = subtaskIdsMap.get(pid)
      if (sids && !sids.includes(taskId)) sids.push(taskId)
      console.warn(
        `[PM] Self-healed orphan: re-parented task "${task.title}" (${taskId}) under "${parent.title}" (${pid})`
      )
    }

    // TaskNotes-created subtasks nest via a `projects[]` link to the parent task
    // note, not our `parentId`/`subtaskIds`. Resolve those after the explicit
    // relationships above so a real parentId always wins.
    this.linkTaskNotesSubtasks(taskMap, childIds)

    const result: Task[] = []
    const pushed = new Set<string>()
    for (const id of topLevelIds) {
      if (pushed.has(id)) continue
      // A subtask can linger in the project's `taskIds` from before it was nested
      // (or from a stale write). Never surface it at top level — it's a child now.
      if (childIds.has(id)) continue
      const task = taskMap.get(id)
      if (task) {
        result.push(task)
        pushed.add(id)
      }
    }
    for (const task of taskMap.values()) {
      if (pushed.has(task.id)) continue
      if (!childIds.has(task.id)) result.push(task)
    }

    return result
  }

  /**
   * TaskNotes writes `blockedBy` uids as `[[wikilinks]]` (by note name or id),
   * while our `dependencies[]`, the Gantt links, and the modal picker all key on
   * the bare task id. Rewrite each captured uid — in both `dependencies` and the
   * preserved `taskNotesBlockedBy` — to the bare id of the task it resolves to, so
   * a TaskNotes-authored dependency renders here. Deduped in the process, which
   * also collapses the bare-id + wikilink pair a prior dual-write can leave behind.
   * Unresolvable refs (a task outside this project) are kept verbatim: preserved
   * for round-trip, just not drawn. Only tasks that carried a `blockedBy` are
   * touched, so a pure-PM load does no extra work.
   */
  private resolveTaskNotesDependencies(taskMap: Map<string, Task>): void {
    const byPath = new Map<string, string>()
    for (const t of taskMap.values()) if (t.filePath) byPath.set(t.filePath, t.id)

    const resolve = (uid: string, sourcePath: string | undefined): string =>
      resolveBlockedByUid(
        uid,
        (id) => taskMap.has(id),
        (inner) => {
          const dest = this.app.metadataCache.getFirstLinkpathDest?.(inner, sourcePath ?? '')
          return dest ? byPath.get(dest.path) : undefined
        }
      )

    for (const task of taskMap.values()) {
      if (!task.taskNotesBlockedBy) continue
      for (const entry of task.taskNotesBlockedBy) entry.uid = resolve(entry.uid, task.filePath)
      const deps: string[] = []
      for (const raw of task.dependencies) {
        const id = resolve(raw, task.filePath)
        if (!deps.includes(id)) deps.push(id)
      }
      task.dependencies = deps
    }
  }

  /**
   * Nest TaskNotes-created subtasks. TaskNotes models a subtask as a note whose
   * `projects[]` links to the *parent task note* (alongside the real project
   * link), rather than via our `parentId`/`subtaskIds`. For every task still at
   * top level, resolve its (foreign) `projects[]` entries: one that lands on
   * another task in this project's map is its parent. Runs after the explicit
   * subtaskIds/parentId nesting so a real relationship always wins, and updates
   * `childIds`/`subtaskIdsMap` so the nested task drops out of the top level.
   * No-op when interop is off — no task carries a foreign `projects` then.
   */
  private linkTaskNotesSubtasks(taskMap: Map<string, Task>, childIds: Set<string>): void {
    if (!this.taskNotesConfig()) return
    const byPath = new Map<string, string>()
    for (const t of taskMap.values()) if (t.filePath) byPath.set(t.filePath, t.id)

    for (const task of taskMap.values()) {
      if (childIds.has(task.id)) continue
      const projects = task.foreign?.projects
      if (!Array.isArray(projects)) continue

      let parentId: string | undefined
      for (const ref of projects) {
        if (typeof ref !== 'string') continue
        const path = resolveTaskNotesRef(this.app, ref, task.filePath ?? '')
        const candidate = path ? byPath.get(path) : undefined
        if (candidate && candidate !== task.id) {
          parentId = candidate
          break
        }
      }
      if (parentId === undefined) continue

      const parent = taskMap.get(parentId)
      if (!parent) continue
      // Guard against a mutual/descendant link forming a cycle.
      if (flattenTasks(task.subtasks).some((f) => f.task.id === parentId)) continue

      parent.subtasks.push(task)
      // The projects[] link owns this relationship; mark it so save never bakes it
      // into our subtaskIds/parentId (which would survive the link's later removal).
      task.viaTaskNotes = true
      childIds.add(task.id)
    }
  }

  /** Resolve a single `blockedBy` uid to a bare task id using a project's index. */
  private resolveUidInProject(uid: string, project: Project, sourcePath?: string): string {
    return resolveBlockedByUid(
      uid,
      (id) => project.taskIndex.has(id),
      (inner) => {
        const dest = this.app.metadataCache.getFirstLinkpathDest?.(inner, sourcePath ?? '')
        if (!dest) return undefined
        for (const [id, entry] of project.taskIndex) if (entry.task.filePath === dest.path) return id
        return undefined
      }
    )
  }

  /**
   * Reconcile a task's dependencies against the `blockedBy` currently on disk,
   * just before we rewrite the file. Another editor (TaskNotes) may have added or
   * removed a blocker since we hydrated; without this, regenerating `blockedBy`
   * from our stale in-memory copy would resurrect a deleted dependency or drop a
   * new one. Mirrors the foreign-key re-read on the same save paths. No-op unless
   * the task carried a `blockedBy` when read.
   */
  private reconcileBlockedByFromDisk(task: Task, fm: Record<string, unknown> | null, project: Project): void {
    if (!task.taskNotesBlockedBy) return
    const disk = parseBlockedBy(fm?.blockedBy).map((d) => ({
      ...d,
      uid: this.resolveUidInProject(d.uid, project, task.filePath)
    }))
    const base = task.taskNotesBlockedBy.map((d) => d.uid)
    task.dependencies = reconcileDependencies(
      base,
      disk.map((d) => d.uid),
      task.dependencies
    )
    // Adopt disk's entries (fresh reltype/gap) as the new base for the next save.
    task.taskNotesBlockedBy = disk
  }

  /**
   * Snapshot the PM-owned fields TaskNotes also writes, so a later save can tell
   * a field PM edited from one TaskNotes changed underneath it. Called on read
   * only when interop is on.
   */
  private captureSharedBase(task: Task): void {
    const base: Record<string, unknown> = {}
    for (const key of TASKNOTES_SHARED_FIELDS) base[key] = task[key]
    task.taskNotesBase = base
  }

  /**
   * Reconcile the PM-owned shared fields against the values currently on disk,
   * just before we rewrite the file. TaskNotes may have changed `priority` /
   * `status` / `due` / `start` since we hydrated; our full-block rewrite would
   * otherwise clobber that edit with our stale copy. Per field, PM wins only when
   * it actually changed the value (memory ≠ base); otherwise the disk value is
   * adopted. Mirrors the foreign-key re-read on the same save paths. No-op unless
   * a base was captured (interop was on at read).
   */
  private reconcileSharedFieldsFromDisk(task: Task, fm: Record<string, unknown> | null): void {
    const base = task.taskNotesBase
    if (!base || !fm) return
    const writable = task as unknown as Record<string, unknown>
    for (const key of TASKNOTES_SHARED_FIELDS) {
      const resolved = reconcileSharedField(base[key], fm[key], task[key])
      writable[key] = resolved
      base[key] = resolved
    }
  }

  /**
   * Maps a bare task id to the `[[note-basename]]` wikilink TaskNotes expects in a
   * `blockedBy` uid. Falls back to the bare id for a task with no file yet or one
   * outside this project's index.
   */
  private blockedByUidResolver(project: Project): (id: string) => string {
    return (id) => {
      const filePath = project.taskIndex.get(id)?.task.filePath
      return filePath ? `[[${noteBasename(filePath)}]]` : id
    }
  }

  async loadTaskFile(
    file: TFile,
    external = false
  ): Promise<{ task: Task | null; subtaskIds: string[]; parentId: string | null }> {
    try {
      const tnConfig = this.taskNotesConfig()
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the body
      // read. The description stays empty until loadTaskBody fills it on modal
      // open, or a 'full' save reads it back inline.
      const timeSync = this.timeSyncEnabled()
      const interop = this.getSettings().taskNotesInterop
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      if (cached && this.isTaskFile(cached, tnConfig)) {
        const result = hydrateTaskFromFile(cached, '', file.path, external, timeSync)
        if (interop) this.captureSharedBase(result.task)
        return result
      }

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || !this.isTaskFile(frontmatter, tnConfig)) {
        return { task: null, subtaskIds: [], parentId: null }
      }

      const result = hydrateTaskFromFile(frontmatter, body, file.path, external, timeSync)
      this.hydratedBodies.add(result.task)
      if (interop) this.captureSharedBase(result.task)
      return result
    } catch (e) {
      if (e instanceof Error && e.message.includes('ENOENT')) {
        console.warn(`[PM] Task file no longer exists, skipping: ${file.path}`)
      } else {
        console.error(`[PM] Failed to load task ${file.path}:`, e)
        new Notice(`Project Manager: Failed to load task "${file.basename}". Check console for details.`)
      }
      return { task: null, subtaskIds: [], parentId: null }
    }
  }

  /**
   * Read the task's file body and populate its description if not already
   * loaded. Modal callers use this to render the real description in one paint.
   * No-op for tasks whose description is already known to match disk.
   */
  async loadTaskBody(task: Task): Promise<void> {
    if (this.hydratedBodies.has(task)) return
    if (!task.filePath) {
      this.hydratedBodies.add(task)
      return
    }
    const file = this.app.vault.getAbstractFileByPath(task.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(task)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { body } = parseFrontmatter(content)
    task.description = stripAutoGeneratedContent(body)
    this.hydratedBodies.add(task)
  }

  /** Same as loadTaskBody but for the project file's body. */
  async loadProjectBody(project: Project): Promise<void> {
    if (this.hydratedBodies.has(project)) return
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(project)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { frontmatter, body } = parseFrontmatter(content)
    const fmDesc = frontmatter?.description
    project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
    this.hydratedBodies.add(project)
  }

  // ─── Save ──────────────────────────────────────────────────────────────────

  async saveProject(project: Project): Promise<void> {
    const key = project.filePath
    const prev = this.saveQueues.get(key) ?? Promise.resolve()
    const next = (async () => {
      await prev
      await this.doSaveProject(project)
    })()
    this.saveQueues.set(
      key,
      (async () => {
        try {
          await next
        } catch {
          // swallow so the next queued save still runs after a failure
        }
      })()
    )
    return next
  }

  private async doSaveProject(project: Project): Promise<void> {
    // Snapshot the dirty map and drop the live entry up front (before any await),
    // so concurrent markDirty calls land in the next save's map, not this one's.
    const dirty = this.dirtyTasks.get(project.filePath) ?? new Map<string, DirtyKind>()
    this.dirtyTasks.delete(project.filePath)

    try {
      project.updatedAt = new Date().toISOString()

      const taskFolder = this.projectTaskFolder(project)
      await this.ensureFolder(taskFolder)

      await this.saveDirtyTasks(project, taskFolder, dirty)

      const file = this.app.vault.getAbstractFileByPath(project.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(project.filePath)
        // Atomic read-modify-write. The mutator recovers the on-disk description
        // when the in-memory project hasn't been hydrated yet.
        await this.app.vault.process(file, (content) => {
          if (!this.hydratedBodies.has(project)) {
            const { frontmatter, body } = parseFrontmatter(content)
            const fmDesc = frontmatter?.description
            project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
          }
          return serializeProject(project, this.statusesFor(project))
        })
        this.hydratedBodies.add(project)
      } else {
        const content = serializeProject(project, this.statusesFor(project))
        this.markSelfWrite(project.filePath)
        await this.app.vault.create(project.filePath, content)
        this.hydratedBodies.add(project)
      }
      // The object we just saved is the canonical in-memory copy (it may be a
      // clone of a previously cached project, e.g. from the project modal).
      this.projectCache.set(project.filePath, project)
    } catch (e) {
      // Save failed. Merge the snapshot back so the next save retries.
      for (const [id, kind] of dirty) this.markDirty(project, [id], kind)
      if (e instanceof TaskFileNameConflictError) throw e
      console.error(`[PM] Failed to save project "${project.title}":`, e)
      new Notice(`Project Manager: Failed to save "${project.title}". Check console for details.`)
      throw e
    }
  }

  /**
   * Write exactly the dirty tasks, located through the O(1) task index instead
   * of walking the whole tree. Writes target distinct files, so they run
   * concurrently — batched.
   */
  private async saveDirtyTasks(project: Project, folder: string, dirty: Map<string, DirtyKind>): Promise<void> {
    // Safety net: a task that has never been written to disk must get a file
    // even if no mutator marked it.
    for (const [id, entry] of project.taskIndex) {
      if (!entry.task.filePath && !dirty.has(id)) dirty.set(id, 'full')
    }
    if (dirty.size === 0) return

    const jobs: { task: Task; parentTask: Task | null; folder: string; kind: DirtyKind }[] = []
    const targetPaths = new Set<string>()
    let hasArchived = false
    for (const [id, kind] of dirty) {
      const entry = project.taskIndex.get(id)
      if (!entry) continue // deleted after being marked dirty
      const { task, parentId } = entry
      const targetFolder = task.archived ? normalizePath(folder + '/Archive') : folder
      if (task.archived) hasArchived = true
      // Two dirty tasks resolving to the same file would race below and surface
      // as a generic create error; detect it up front and keep the typed error.
      const path = normalizePath(resolveTaskPath(task, targetFolder, task.filePath))
      if (targetPaths.has(path)) throw new TaskFileNameConflictError(path)
      targetPaths.add(path)
      jobs.push({ task, parentTask: parentId ? findTaskById(project, parentId) : null, folder: targetFolder, kind })
    }
    if (hasArchived) await this.ensureFolder(normalizePath(folder + '/Archive'))

    const errors: Error[] = []
    const batchSize = 16
    for (let i = 0; i < jobs.length; i += batchSize) {
      const results = await Promise.allSettled(
        jobs.slice(i, i + batchSize).map((j) => this.saveTaskFile(j.task, project, j.parentTask, j.folder, j.kind))
      )
      for (const r of results) {
        if (r.status === 'rejected') errors.push(r.reason instanceof Error ? r.reason : new Error(String(r.reason)))
      }
    }
    if (errors.length) {
      if (errors.length === 1 && errors[0] instanceof TaskFileNameConflictError) throw errors[0]
      throw new Error(`Failed to save ${errors.length} task(s): ${errors.map((e) => e.message).join('; ')}`)
    }
  }

  private async saveTaskFile(
    task: Task,
    project: Project,
    parentTaskArg: Task | null,
    folder: string,
    kind: DirtyKind
  ): Promise<void> {
    // A TaskNotes-linked child owns its parentage through its projects[] link, not
    // our parentId — write it as a project-level note so we never bake the relation.
    const parentTask = task.viaTaskNotes ? null : parentTaskArg
    const previousPath = task.filePath
    const filePath = normalizePath(resolveTaskPath(task, folder, previousPath))
    const renamed = previousPath !== undefined && previousPath !== filePath
    const blockedByUid = this.blockedByUidResolver(project)
    const timeSync = this.timeSyncEnabled()

    try {
      // Frontmatter-only fast path: leave the body alone entirely.
      if (kind === 'fm' && previousPath && !renamed) {
        const existing = this.app.vault.getAbstractFileByPath(filePath)
        if (existing instanceof TFile) {
          this.markSelfWrite(filePath)
          await this.app.fileManager.processFrontMatter(existing, (fm: Record<string, unknown>) => {
            // Re-read foreign keys off the file: another plugin may have written
            // its own since we hydrated this task, and we're about to wipe the block.
            task.foreign = collectForeign(fm, undefined, timeSync)
            this.reconcileBlockedByFromDisk(task, fm, project)
            this.reconcileSharedFieldsFromDisk(task, fm)
            const next = buildTaskFrontmatter(task, project, parentTask, this.taskNotesConfig(), blockedByUid, timeSync)
            for (const k of Object.keys(fm)) Reflect.deleteProperty(fm, k)
            Object.assign(fm, next)
          })
          return
        }
        // File missing somehow; fall through to recreate it.
      }

      const existing = this.app.vault.getAbstractFileByPath(filePath)
      if (existing instanceof TFile && existing.path !== previousPath) {
        throw new TaskFileNameConflictError(filePath)
      }

      if (existing instanceof TFile) {
        // In-place full rewrite, atomic. Recover description from disk when not hydrated.
        this.markSelfWrite(filePath)
        await this.app.vault.process(existing, (content) => {
          const { frontmatter, body } = parseFrontmatter(content)
          if (!this.hydratedBodies.has(task)) {
            task.description = stripAutoGeneratedContent(body)
          }
          // Same reasoning as the fast path: the file's foreign keys win over our copy.
          task.foreign = collectForeign(frontmatter ?? {}, undefined, timeSync)
          this.reconcileBlockedByFromDisk(task, frontmatter, project)
          this.reconcileSharedFieldsFromDisk(task, frontmatter)
          return serializeTask(
            task,
            project,
            parentTask,
            this.statusesFor(project),
            this.taskNotesConfig(),
            blockedByUid,
            timeSync
          )
        })
      } else {
        // New file or rename target. For a rename of an unhydrated task, read
        // the old file once to recover the description before creating the new one.
        if (!this.hydratedBodies.has(task) && previousPath) {
          const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
          if (oldFile instanceof TFile) {
            const content = await this.app.vault.cachedRead(oldFile)
            task.description = stripAutoGeneratedContent(parseFrontmatter(content).body)
          }
        }
        const content = serializeTask(
          task,
          project,
          parentTask,
          this.statusesFor(project),
          this.taskNotesConfig(),
          blockedByUid,
          timeSync
        )
        this.markSelfWrite(filePath)
        await this.app.vault.create(filePath, content)
      }
      task.filePath = filePath
      this.hydratedBodies.add(task)

      if (renamed && previousPath) {
        const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
        if (oldFile instanceof TFile) {
          this.markSelfWrite(previousPath)
          await this.app.fileManager.trashFile(oldFile)
        }
        // Keep the task's attachment folder with the renamed note.
        this.markSelfWrite(this.taskFolder(previousPath))
        this.markSelfWrite(this.taskFolder(filePath))
        await moveTaskAttachmentFolder(this.app, previousPath, filePath)
      }
    } catch (e) {
      if (!(e instanceof TaskFileNameConflictError)) {
        console.error(`[PM] Failed to save task "${task.title}" (${task.id}):`, e)
      }
      throw e
    }
  }

  /**
   * Pre-flight check: would saving this task (at its current title) collide
   * with another file already in the vault? Returns a typed error callers can
   * surface inline, or null if the save would proceed cleanly.
   */
  findTaskFileConflict(project: Project, task: Task): TaskFileNameConflictError | null {
    const baseFolder = this.projectTaskFolder(project)
    const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
    const desired = normalizePath(resolveTaskPath(task, folder, task.filePath))
    if (desired === task.filePath) return null
    const existing = this.app.vault.getAbstractFileByPath(desired)
    return existing instanceof TFile ? new TaskFileNameConflictError(desired) : null
  }

  // ─── CRUD shortcuts ────────────────────────────────────────────────────────

  async createProject(title: string, folder: string): Promise<Project> {
    const safeName = title.replace(/[\\/:*?"<>|]/g, '-')
    const filePath = normalizePath(`${folder}/${safeName}.md`)
    const project = makeProject(title, filePath)
    await this.ensureFolder(this.projectTaskFolder(project))
    await this.saveProject(project)
    return project
  }

  async insertTask(project: Project, task: Task, parentId: string | null = null): Promise<void> {
    if (!task.completed && isTerminalStatus(task.status, this.statusesFor(project))) {
      task.completed = today().toString()
    }
    this.hydratedBodies.add(task)
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id], 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Convert an arbitrary vault note into a top-level task file in the project's
   * tasks folder. The note body becomes the task description; notes that are
   * already pm-tasks are skipped. The task is picked up on the next project
   * load via the orphan self-heal, matching how the tasks folder is scanned.
   */
  async importNoteAsTask(project: Project, file: TFile, opts: ImportNoteOptions): Promise<'imported' | 'skipped'> {
    const content = await this.app.vault.read(file)
    const { frontmatter, body } = parseFrontmatter(content)
    if (frontmatter?.[TASK_FRONTMATTER_KEY] === true) return 'skipped'

    const task = makeTask({
      title: file.basename,
      description: body,
      status: opts.status,
      priority: opts.priority,
      // The note may already be a TaskNotes task; keep whatever it had.
      foreign: collectForeign(frontmatter ?? {})
    })
    const folder = this.projectTaskFolder(project)
    await this.ensureFolder(folder)
    const newFilePath = taskFilePath(task.title, folder)
    const newContent = serializeTask(task, project, null, this.statusesFor(project), this.taskNotesConfig())

    if (opts.handling === 'move') {
      await this.app.fileManager.renameFile(file, newFilePath)
      const moved = this.app.vault.getAbstractFileByPath(newFilePath)
      if (moved instanceof TFile) {
        await this.app.vault.process(moved, () => newContent)
      }
    } else {
      await this.app.vault.create(newFilePath, newContent)
    }
    return 'imported'
  }

  async duplicateTask(project: Project, sourceId: string, includeSubtasks: boolean): Promise<Task | null> {
    const source = findTaskById(project, sourceId)
    if (!source) return null
    const copy = cloneTaskSubtree(source, includeSubtasks)
    // Every task in a project shares one flat folder and its filename comes from
    // the title slug, so a clone that keeps the source title would write over the
    // original. Reserve a free "(copy)" title for the whole subtree, not just the
    // root, and across the clones we're about to add so siblings don't collide.
    const baseFolder = this.projectTaskFolder(project)
    const claimed = new Set<string>()
    const usedTitles = new Set(flattenTasks(project.tasks).map((f) => f.task.title))
    const claimName = (task: Task): void => {
      const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
      this.assignCopyName(task, folder, usedTitles, claimed)
    }
    // Clones don't have a filePath yet; their description in memory is whatever
    // came from the source. We need to write that body verbatim.
    claimName(copy)
    this.hydratedBodies.add(copy)
    for (const ft of flattenTasks(copy.subtasks)) {
      claimName(ft.task)
      this.hydratedBodies.add(ft.task)
    }
    const parentId = findParentId(project, sourceId)
    addTaskToTree(project.tasks, copy, parentId)
    moveTaskInTree(project.tasks, copy.id, sourceId, 'after')
    indexAddSubtree(project, copy, parentId)
    // Copy and every cloned descendant are new files.
    this.markSubtreeDirty(project, copy.id, 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
    return copy
  }

  private assignCopyName(task: Task, folder: string, usedTitles: Set<string>, claimed: Set<string>): void {
    const base = task.title.replace(/(?: \(copy(?: \d+)?\))+$/, '')
    for (let n = 1; ; n++) {
      const suffix = n === 1 ? ' (copy)' : ` (copy ${n})`
      const room = TASK_SLUG_MAX_LENGTH - suffix.length
      const title = (base.length > room ? base.slice(0, room).trimEnd() : base) + suffix
      const path = normalizePath(taskFilePath(title, folder))
      if (
        !usedTitles.has(title) &&
        !claimed.has(path) &&
        !(this.app.vault.getAbstractFileByPath(path) instanceof TFile)
      ) {
        usedTitles.add(title)
        claimed.add(path)
        task.title = title
        return
      }
    }
  }

  async moveTask(project: Project, taskId: string, newParentId: string | null): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    const oldParentId = findParentId(project, taskId)
    deleteTaskFromTree(project.tasks, taskId)
    addTaskToTree(project.tasks, task, newParentId)
    indexSetParent(project, taskId, newParentId)
    // Moved task's parentId is in frontmatter but its body's Parent: link also changes.
    this.markDirty(project, [taskId], 'full')
    // Old and new parents' bodies (Subtasks list) change.
    if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  async moveTasks(project: Project, taskIds: string[], newParentId: string | null): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const oldParentId = findParentId(project, id)
      deleteTaskFromTree(project.tasks, id)
      addTaskToTree(project.tasks, task, newParentId)
      indexSetParent(project, id, newParentId)
      this.markDirty(project, [id], 'full')
      if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    }
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Stamp or clear `completed` based on a status transition. Mutates `patch` so the
   * date lands in the same save as the status change. A patch that changes
   * `completed` away from the task's current value (a manual edit in the modal, or
   * an import) wins and is left untouched; otherwise crossing the
   * complete/incomplete boundary stamps today's date or clears it.
   *
   * The modal saves the whole task as the patch, so `patch.completed` is almost
   * always present and equal to the stored value — comparing against the task,
   * not just checking presence, is what lets auto-stamping fire from the modal.
   */
  private stampCompletion(project: Project, task: Task, patch: Partial<Task>): void {
    if (patch.status === undefined) return
    if (patch.completed !== undefined && patch.completed !== task.completed) return
    const statuses = this.statusesFor(project)
    const wasComplete = isTerminalStatus(task.status, statuses)
    const nowComplete = isTerminalStatus(patch.status, statuses)
    if (nowComplete && !wasComplete) patch.completed = today().toString()
    else if (!nowComplete && wasComplete) patch.completed = ''
  }

  async updateTask(project: Project, taskId: string, patch: Partial<Task>): Promise<void> {
    const task = findTaskById(project, taskId)
    const oldTitle = task?.title
    if (task) this.stampCompletion(project, task, patch)
    // The task editor saves the whole task, so a patch can add, rename, remove,
    // or reorder subtasks. Snapshot the pre-edit subtree to diff against once the
    // tree has the new one.
    const oldSubtree = task && patch.subtasks !== undefined ? flattenTasks(task.subtasks).map((f) => f.task) : []
    updateTaskInTree(project.tasks, taskId, patch)
    const titleChanged = task && patch.title !== undefined && patch.title !== oldTitle
    // Title change renames the file, which forces the rename branch in saveTaskFile
    // (body rewrite). Description/archived/subtasks patches require a body rewrite too.
    const kind: DirtyKind = patchNeedsBodyRewrite(patch) || titleChanged ? 'full' : 'fm'
    this.markDirty(project, [taskId], kind)
    // Patch-set description is the caller's intent; trust it as the new body.
    if (task && patch.description !== undefined) this.hydratedBodies.add(task)
    if (task && patch.subtasks !== undefined) {
      // Re-index the saved subtree and create/rename/trash the affected subtask
      // files; this also covers the children's Parent-link rewrite on a rename.
      await this.reconcileSubtasks(project, task, oldSubtree)
    } else if (task && titleChanged) {
      // Title change renames the file, which breaks direct children's Parent link.
      for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
    }
    await this.saveProject(project)
  }

  /**
   * After a save that carries a task's whole subtree (the task editor works on a
   * deep clone), make the index and the on-disk files match it: re-point the
   * index at the saved subtree objects, mark new/renamed/restatused subtasks for
   * a write, and trash the files of subtasks removed in the editor. Unchanged
   * subtasks aren't rewritten.
   */
  private async reconcileSubtasks(project: Project, parent: Task, oldSubtree: Task[]): Promise<void> {
    indexAddSubtree(project, parent, findParentId(project, parent.id))

    const old = new Map(oldSubtree.map((t) => [t.id, t]))
    const liveIds = new Set<string>()
    for (const { task } of flattenTasks(parent.subtasks)) {
      liveIds.add(task.id)
      const prev = old.get(task.id)
      if (!prev) {
        // Brand-new subtask: it needs its own file, body included.
        this.hydratedBodies.add(task)
        this.markDirty(project, [task.id], 'full')
      } else if (prev.title !== task.title) {
        this.markDirty(project, [task.id], 'full')
      } else if (prev.status !== task.status || prev.completed !== task.completed || prev.progress !== task.progress) {
        this.markDirty(project, [task.id], 'fm')
      }
    }

    const folder = this.projectTaskFolder(project)
    for (const removed of oldSubtree) {
      if (liveIds.has(removed.id)) continue
      project.taskIndex.delete(removed.id)
      // The flat snapshot already lists every descendant, so trash this file only.
      if (removed.filePath) await this.deleteTaskFiles({ ...removed, subtasks: [] }, folder)
    }
  }

  /**
   * Apply a patch to several tasks in one save. `patch` may be a function
   * producing a per-task patch; return null to leave that task untouched.
   */
  async updateTasks(
    project: Project,
    taskIds: string[],
    patch: Partial<Task> | ((task: Task) => Partial<Task> | null)
  ): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const raw = typeof patch === 'function' ? patch(task) : patch
      if (!raw) continue
      // Copy a shared patch object before stamping so one task's completion date
      // doesn't bleed onto the next iteration through the same reference.
      const p = { ...raw }
      this.stampCompletion(project, task, p)
      const oldTitle = task.title
      updateTaskInTree(project.tasks, id, p)
      const titleChanged = p.title !== undefined && p.title !== oldTitle
      const kind: DirtyKind = patchNeedsBodyRewrite(p) || titleChanged ? 'full' : 'fm'
      this.markDirty(project, [id], kind)
      if (p.description !== undefined) this.hydratedBodies.add(task)
      if (titleChanged) {
        for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
      }
    }
    await this.saveProject(project)
  }

  /**
   * Move a task before/after a sibling. Sibling order persists in the parent's
   * subtaskIds (or the project file's taskIds for top-level tasks), so only the
   * parent needs a rewrite.
   */
  async reorderTask(project: Project, taskId: string, targetId: string, position: 'before' | 'after'): Promise<void> {
    if (!moveTaskInTree(project.tasks, taskId, targetId, position)) return
    const parentId = findParentId(project, targetId)
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  async deleteTasks(project: Project, taskIds: string[]): Promise<void> {
    const folder = this.projectTaskFolder(project)
    const dirtyParents = new Set<string>()
    for (const id of taskIds) {
      const parentId = findParentId(project, id)
      if (parentId) dirtyParents.add(parentId)
      const task = findTaskById(project, id)
      if (task) {
        await this.deleteTaskFiles(task, folder)
        indexRemoveSubtree(project, task)
      }
      deleteTaskFromTree(project.tasks, id)
    }
    // Parents' bodies (Subtasks list) shrink.
    if (dirtyParents.size) this.markDirty(project, dirtyParents, 'full')
    await this.saveProject(project)
  }

  async archiveTask(project: Project, taskId: string): Promise<void> {
    await doArchiveTask(this.app, project, taskId)
  }

  async unarchiveTask(project: Project, taskId: string): Promise<void> {
    await doUnarchiveTask(this.app, project, taskId)
  }

  async deleteTask(project: Project, taskId: string): Promise<void> {
    const parentId = findParentId(project, taskId)
    const task = findTaskById(project, taskId)
    if (task) {
      await this.deleteTaskFiles(task, this.projectTaskFolder(project))
      indexRemoveSubtree(project, task)
    }
    deleteTaskFromTree(project.tasks, taskId)
    // Parent's Subtasks list shrinks.
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  private async deleteTaskFiles(task: Task, folder: string): Promise<void> {
    for (const sub of task.subtasks) {
      await this.deleteTaskFiles(sub, folder)
    }
    if (task.filePath) {
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(task.filePath)
        await this.app.fileManager.trashFile(file)
      }
      // Trash the task's own folder (its attachments) alongside the note.
      const taskDir = this.app.vault.getAbstractFileByPath(this.taskFolder(task.filePath))
      if (taskDir instanceof TFolder) {
        await this.deleteFolderRecursive(taskDir)
      }
    }
  }

  /** A task's own folder, holding its attachments: the task file path minus `.md`. */
  private taskFolder(taskFilePath: string): string {
    return taskFilePath.replace(/\.md$/, '')
  }

  /**
   * Save a pasted or dropped file under the task's own `attachments` folder,
   * keeping it with the task instead of Obsidian's vault-wide default attachment
   * location. Returns the created file so the caller can embed it.
   */
  async saveTaskAttachment(project: Project, task: Task, fileName: string, data: ArrayBuffer): Promise<TFile> {
    const taskPath = task.filePath ?? taskFilePath(task.title, this.projectTaskFolder(project))
    const dir = normalizePath(`${this.taskFolder(taskPath)}/attachments`)
    this.markSelfWrite(this.taskFolder(taskPath))
    this.markSelfWrite(dir)
    await this.ensureFolder(dir)
    const path = this.uniqueChildPath(dir, fileName)
    this.markSelfWrite(path)
    return this.app.vault.createBinary(path, data)
  }

  private uniqueChildPath(folder: string, fileName: string): string {
    const dot = fileName.lastIndexOf('.')
    const base = dot > 0 ? fileName.slice(0, dot) : fileName
    const ext = dot > 0 ? fileName.slice(dot) : ''
    let candidate = normalizePath(`${folder}/${base}${ext}`)
    for (let n = 1; this.app.vault.getAbstractFileByPath(candidate); n++) {
      candidate = normalizePath(`${folder}/${base} ${n}${ext}`)
    }
    return candidate
  }

  async deleteProject(project: Project): Promise<void> {
    const taskFolder = this.projectTaskFolder(project)
    const folder = this.app.vault.getAbstractFileByPath(taskFolder)
    if (folder instanceof TFolder) {
      await this.deleteFolderRecursive(folder)
    }
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (file instanceof TFile) {
      this.markSelfWrite(project.filePath)
      await this.app.fileManager.trashFile(file)
    }
    this.clearDirty(project)
    this.saveQueues.delete(project.filePath)
    this.projectCache.delete(project.filePath)
  }

  private async deleteFolderRecursive(folder: TFolder): Promise<void> {
    for (const child of folder.children.slice()) {
      if (child instanceof TFile) {
        this.markSelfWrite(child.path)
        await this.app.fileManager.trashFile(child)
      } else if (child instanceof TFolder) {
        await this.deleteFolderRecursive(child)
      }
    }
    await this.app.fileManager.trashFile(folder)
  }

  // ─── Scheduling ──────────────────────────────────────────────────────────

  /**
   * Run dependency-based scheduling on the project. Applies computed date
   * patches and saves; returns the number of tasks that were adjusted.
   * A no-op when auto-scheduling is off for this project, so callers can
   * invoke it unconditionally after a change.
   */
  async scheduleAfterChange(project: Project, changedTaskId?: string): Promise<number> {
    const config = this.configFor(project)
    if (!config.autoSchedule) return 0
    const { patches } = computeSchedule(project.tasks, changedTaskId, config.statuses)
    if (patches.length === 0) return 0

    for (const p of patches) {
      updateTaskInTree(project.tasks, p.taskId, { start: p.start, due: p.due })
      // Dates live in frontmatter only.
      this.markDirty(project, [p.taskId], 'fm')
    }
    await this.saveProject(project)
    return patches.length
  }
}
