import { MINUTES_PER_HOUR, type Project, type ProjectConfig, type StatusConfig, type Task } from '../types'
import { mergeBlockedBy, mergeProjectLink, stampTaskNotesMarker, type TaskNotesConfig } from '../integrations/tasknotes'
import { isTerminalStatus, sanitizeFileName } from '../utils'
import { appendYaml, FRONTMATTER_KEY, stripAutoGeneratedContent, TASK_FRONTMATTER_KEY } from './YamlParser'

// ─── Serialize ──────────────────────────────────────────────────────────────

/** Only the fields a project actually overrides are written; an empty override block is omitted. */
function serializeProjectConfig(config: ProjectConfig | undefined): Record<string, unknown> | null {
  if (!config) return null
  const out: Record<string, unknown> = {}
  if (config.statuses?.length) out.statuses = config.statuses
  if (config.priorities?.length) out.priorities = config.priorities
  if (config.defaultView) out.defaultView = config.defaultView
  if (config.autoSchedule !== undefined) out.autoSchedule = config.autoSchedule
  if (config.kanbanShowSubtasks !== undefined) out.kanbanShowSubtasks = config.kanbanShowSubtasks
  if (config.kanbanShowDescriptionPreview !== undefined) {
    out.kanbanShowDescriptionPreview = config.kanbanShowDescriptionPreview
  }
  return Object.keys(out).length ? out : null
}

export function serializeProject(project: Project, statuses: StatusConfig[] = []): string {
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => t.id)

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }
  const config = serializeProjectConfig(project.config)
  if (config) fm.config = config

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const basename = noteBasename(t.filePath)
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function buildTaskFrontmatter(
  task: Task,
  project: Project,
  parentTask: Task | null,
  taskNotes: TaskNotesConfig | null = null,
  blockedByUid?: (id: string) => string,
  timeSync = false
): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    // A child nested purely via a TaskNotes projects[] link is not ours to record:
    // baking it here would resurrect the relationship after the link is removed.
    subtaskIds: task.subtasks.filter((s) => !s.viaTaskNotes).map((s) => s.id),
    dependencies: task.dependencies,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  if (task.completed) fm.completed = task.completed
  if (task.recurrence) fm.recurrence = task.recurrence
  // With time sync on, TaskNotes' shape is canonical: write the estimate back as
  // minutes and the sessions as `timeEntries`, leaving `timeLogs` unwritten so the
  // two representations can't drift. Off, PM keeps its hours + per-day `timeLogs`.
  if (task.timeEstimate !== undefined) {
    fm.timeEstimate = timeSync ? Math.round(task.timeEstimate * MINUTES_PER_HOUR) : task.timeEstimate
  }
  if (timeSync) {
    if (task.timeEntries?.length) fm.timeEntries = task.timeEntries
  } else if (task.timeLogs?.length) {
    fm.timeLogs = task.timeLogs
  }
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields
  // Regenerate TaskNotes' RFC 9253 `blockedBy` from the entries we captured on
  // read, reconciled against our current `dependencies[]`: kept relations keep
  // their reltype/gap, removed deps fall away, added deps get FS/P0D defaults.
  // Uids are written as `[[note-basename]]` (via `blockedByUid`) so TaskNotes
  // resolves them; `dependencies` above stays as bare ids for PM-only readers.
  //
  // Emit when either side has something to write: a captured `blockedBy` is
  // preserved even with interop off (it's stripped from `foreign` on read, so
  // this is its only round-trip path), while a PM-native dependency is exported
  // only when interop is on — so a non-TaskNotes vault never gains a stray
  // `blockedBy`, and a task with no deps never writes a noisy empty array.
  if (task.taskNotesBlockedBy?.length || (taskNotes && task.dependencies.length)) {
    fm.blockedBy = mergeBlockedBy(task.taskNotesBlockedBy ?? [], task.dependencies, blockedByUid)
  }
  // Another plugin's keys, carried through untouched. Written last, and never
  // over a field we own — a foreign `recurrence` only lands when we have none.
  if (task.foreign) {
    for (const [key, value] of Object.entries(task.foreign)) {
      if (key in fm) continue
      fm[key] = value
    }
  }
  // Dual identifier + project link: make the file visible to TaskNotes too.
  // Applied last, after the foreign copy, so our entries sit over — and merge
  // with — whatever tag/property/`projects` already round-tripped.
  if (taskNotes) {
    stampTaskNotesMarker(fm, taskNotes)
    // Current basename (not cached) so the link tracks a project rename for free.
    fm.projects = mergeProjectLink(fm.projects, noteBasename(project.filePath))
    // TaskNotes models a subtask as a `projects[]` link to the parent *task*
    // note (alongside the real project link) — its getTasksLinkedToProject reads
    // exactly this field. Regenerated from the parent's current path on every
    // save of *this* (child) task, so a parent rename only propagates once the
    // child is next saved, and a pre-existing subtask gains the link on its next
    // save. Removal isn't symmetric either: clearing `parentId` won't strip a
    // stale link, since mergeProjectLink only ever adds.
    if (parentTask?.filePath) {
      fm.projects = mergeProjectLink(fm.projects, noteBasename(parentTask.filePath))
    }
  }
  return fm
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[] = [],
  taskNotes: TaskNotesConfig | null = null,
  blockedByUid?: (id: string) => string,
  timeSync = false
): string {
  const fm = buildTaskFrontmatter(task, project, parentTask, taskNotes, blockedByUid, timeSync)

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  if (parentTask?.filePath) {
    yamlLines.push(`Parent: [[${noteBasename(parentTask.filePath)}|${parentTask.title}]]`)
  } else {
    yamlLines.push(`Project: [[${noteBasename(project.filePath)}|${project.title}]]`)
  }

  // TaskNotes-linked children are excluded from our subtaskIds (see buildTaskFrontmatter);
  // keep the body list in step so the two representations can't drift.
  const ownSubtasks = task.subtasks.filter((s) => !s.viaTaskNotes)
  if (ownSubtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of ownSubtasks) {
      const subBasename = sub.filePath ? noteBasename(sub.filePath) : taskSlug(sub.title)
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`)
    }
  }

  return yamlLines.join('\n')
}

/** A vault file path's basename without its `.md` extension, for `[[wikilinks]]`. */
export function noteBasename(filePath: string): string {
  return filePath.replace(/^.*\//, '').replace(/\.md$/, '')
}

/** Slug length cap, for path-length safety (Windows MAX_PATH, mobile, sync). */
export const TASK_SLUG_MAX_LENGTH = 60

/**
 * PM's file-naming scheme: a lowercase, hyphenated, length-capped slug of the
 * title. Idempotent on its own output, so a basename PM produced is exactly one
 * for which `taskSlug(basename) === basename` — the test used to tell a
 * PM-named file apart from a human- or TaskNotes-named one.
 */
export function taskSlug(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, TASK_SLUG_MAX_LENGTH)
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${taskSlug(taskTitle)}.md`
}
