import {
  type CustomFieldDef,
  makeTask,
  MINUTES_PER_HOUR,
  type PriorityConfig,
  type Project,
  type ProjectConfig,
  type SavedView,
  type StatusConfig,
  type Task,
  type TimeEntry,
  type ViewMode
} from '../types'
import { parseBlockedBy } from '../integrations/tasknotes'
import { stripAutoGeneratedContent, TASK_FRONTMATTER_KEY, TASK_OWNED_KEYS } from './YamlParser'

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      const viewMode = v.viewMode
      const validViewMode: ViewMode | undefined =
        viewMode === 'table' || viewMode === 'gantt' || viewMode === 'kanban' ? viewMode : undefined
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
        ...(validViewMode ? { viewMode: validViewMode } : {})
      }
    })
}

/**
 * Obsidian's `FrontMatterCache` carries the YAML block's source range under
 * `position`. It isn't a frontmatter key and must never be written back.
 */
const CACHE_ARTIFACT_KEYS: ReadonlySet<string> = new Set(['position'])

/**
 * Everything in the frontmatter we don't model, deep-copied so a later in-place
 * edit can't reach back into Obsidian's live metadataCache object. `recurrence`
 * joins the set when it isn't our object shape — TaskNotes stores an RRULE
 * string there, and we'd rather pass it through than coerce or drop it.
 *
 * `pmAuthored` marks a file PM owns (`pm-task: true`). On a file we don't own —
 * a TaskNotes task shared in with no marker — `timeEstimate` is TaskNotes' key
 * in *minutes*, not our *hours*, so we pass it through as foreign rather than
 * misread it 60× (see `mapRawToTask`). Defaults to self-deriving from the marker;
 * the inline-tasks path forces it true since embedded PM tasks carry no marker.
 *
 * `timeShapeMinutes` (this vault's files are in TaskNotes' minutes shape — see
 * `timeShapeIsMinutes`) makes TaskNotes' time shape canonical: `timeEntries`
 * becomes ours (kept out of foreign so we don't double-write it), and `timeEstimate`
 * is ours regardless of `pmAuthored` since we now read its minutes.
 */
export function collectForeign(
  r: Record<string, unknown>,
  pmAuthored = r[TASK_FRONTMATTER_KEY] === true,
  timeShapeMinutes = false
): Record<string, unknown> | undefined {
  const foreign: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(r)) {
    if (value === undefined || CACHE_ARTIFACT_KEYS.has(key)) continue
    if (timeShapeMinutes && key === 'timeEntries') continue
    const owned =
      key === 'recurrence'
        ? isOwnRecurrence(value)
        : key === 'timeEstimate'
          ? pmAuthored || timeShapeMinutes
          : TASK_OWNED_KEYS.has(key)
    if (owned) continue
    foreign[key] = structuredClone(value)
  }
  return Object.keys(foreign).length ? foreign : undefined
}

function isOwnRecurrence(value: unknown): boolean {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

/**
 * Fold TaskNotes' RFC 9253 `blockedBy` into our model: capture the full typed
 * array, union its uids onto `dependencies` (our field first, its uids appended,
 * deduped), and drop `blockedBy` from `foreign` so serialize regenerates it from
 * the captured copy rather than passing through a now-stale duplicate. An empty
 * parse (missing/malformed) leaves `blockedBy` in `foreign` for verbatim passthrough.
 */
function foldBlockedBy(
  r: Record<string, unknown>,
  foreign: Record<string, unknown> | undefined,
  dependencies: string[]
): Pick<Task, 'foreign' | 'dependencies' | 'taskNotesBlockedBy'> {
  const blockedBy = parseBlockedBy(r.blockedBy)
  if (!blockedBy.length) return { foreign, dependencies }
  const deps = [...dependencies]
  for (const { uid } of blockedBy) {
    if (!deps.includes(uid)) deps.push(uid)
  }
  let nextForeign = foreign
  if (nextForeign && 'blockedBy' in nextForeign) {
    const rest = { ...nextForeign }
    delete rest.blockedBy
    nextForeign = Object.keys(rest).length ? rest : undefined
  }
  return { foreign: nextForeign, dependencies: deps, taskNotesBlockedBy: blockedBy }
}

/**
 * Read `timeEstimate` into our hours field. When the vault is in minutes shape
 * (`timeShapeMinutes`) the raw value is TaskNotes' minutes, converted to hours;
 * otherwise it's ours (hours) but only on a PM-authored file — a shared-in
 * TaskNotes estimate stays foreign (see the 60× misread guarded in `collectForeign`).
 */
function readTimeEstimate(value: unknown, pmAuthored: boolean, timeShapeMinutes: boolean): number | undefined {
  if (typeof value !== 'number') return undefined
  if (timeShapeMinutes) return value / MINUTES_PER_HOUR
  return pmAuthored ? value : undefined
}

/**
 * At the moment PM first authors a note that came in from TaskNotes, its foreign
 * `timeEstimate` is TaskNotes' *minutes* — but this save stamps `pm-task`, and on
 * the next load a pm-authored file's `timeEstimate` is read as our *hours*, so
 * those minutes would silently become a 60× estimate. Claim it here at the adoption
 * moment: drop the foreign copy (PM owns the field now) and, when we hold no
 * estimate of our own, convert its minutes into our hours.
 *
 * A no-op in minutes shape — there `collectForeign` never files `timeEstimate`
 * under foreign, since the whole vault already reads/writes minutes.
 */
export function adoptForeignTimeEstimate(task: Task, timeShapeMinutes: boolean): void {
  if (timeShapeMinutes) return
  const foreign = task.foreign
  if (!foreign || !('timeEstimate' in foreign)) return
  const minutes = foreign.timeEstimate
  const rest = { ...foreign }
  delete rest.timeEstimate
  task.foreign = Object.keys(rest).length ? rest : undefined
  if (task.timeEstimate === undefined && typeof minutes === 'number') {
    task.timeEstimate = minutes / MINUTES_PER_HOUR
  }
}

/**
 * Hydrate TaskNotes' `timeEntries` into typed sessions. Each entry needs a
 * non-empty string `startTime`; `endTime` is optional (absent = running) and
 * `description` defaults to empty. Malformed entries are skipped; a value that
 * yields none returns undefined so the field stays unset.
 */
function mapTimeEntries(value: unknown): TimeEntry[] | undefined {
  if (!Array.isArray(value)) return undefined
  const out: TimeEntry[] = []
  for (const entry of value) {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) continue
    const e = entry as Record<string, unknown>
    if (typeof e.startTime !== 'string' || !e.startTime) continue
    const te: TimeEntry = {
      startTime: e.startTime,
      description: typeof e.description === 'string' ? e.description : ''
    }
    if (typeof e.endTime === 'string' && e.endTime) te.endTime = e.endTime
    out.push(te)
  }
  return out.length ? out : undefined
}

/**
 * Map raw frontmatter fields to a Task, with optional overrides. `pmAuthored`
 * (self-derived from the `pm-task` marker, forced true for inline tasks) decides
 * whether `timeEstimate` is read as ours (hours) or left to `foreign` — see
 * `collectForeign`. `timeShapeMinutes` (this vault's files are in TaskNotes' minutes
 * shape — see `timeShapeIsMinutes`) adopts TaskNotes' time shape: `timeEstimate` is
 * read as minutes and converted to our hours, and `timeEntries` sessions are
 * hydrated as the canonical time record.
 */
export function mapRawToTask(
  r: Record<string, unknown>,
  overrides?: Partial<Task>,
  pmAuthored = r[TASK_FRONTMATTER_KEY] === true,
  timeShapeMinutes = false
): Task {
  return makeTask({
    ...foldBlockedBy(
      r,
      collectForeign(r, pmAuthored, timeShapeMinutes),
      Array.isArray(r.dependencies) ? [...(r.dependencies as string[])] : []
    ),
    id: r.id as string,
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone' : (r.type as string) === 'subtask' ? 'subtask' : 'task',
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: (r.completed as string) ?? '',
    // Copy container fields rather than aliasing them. On the metadataCache
    // fast path `r` is Obsidian's live frontmatter object, so a shared array or
    // object would let an in-place task mutation corrupt the cache.
    assignees: Array.isArray(r.assignees) ? [...(r.assignees as string[])] : [],
    tags: Array.isArray(r.tags) ? [...(r.tags as string[])] : [],
    subtasks: [],
    recurrence: isOwnRecurrence(r.recurrence)
      ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
      : undefined,
    timeEstimate: readTimeEstimate(r.timeEstimate, pmAuthored, timeShapeMinutes),
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[]).map((log) => ({ ...log }))
      : undefined,
    timeEntries: timeShapeMinutes ? mapTimeEntries(r.timeEntries) : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    // Inline tasks live in a PM project file and carry no `pm-task` marker of
    // their own, but are always PM-owned — force `pmAuthored` so their hours
    // `timeEstimate` isn't mistaken for a TaskNotes minutes value.
    return mapRawToTask(
      rec,
      { subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : [] },
      true
    )
  })
}

/**
 * A stable task id derived from a note's vault path, for a shared TaskNotes note
 * that carries no PM `id`. Deterministic so the same file hydrates to the same id
 * across reloads (no churn in the project's `taskIds`), and — crucially — never
 * `undefined`, which would serialize as an empty `taskIds` element and corrupt the
 * project's YAML with a stray comma. Persisted as a real `id` on the next save.
 */
export function deriveTaskIdFromPath(filePath: string): string {
  let hash = 0
  for (let i = 0; i < filePath.length; i++) {
    hash = (Math.imul(31, hash) + filePath.charCodeAt(i)) | 0
  }
  return 'tn' + (hash >>> 0).toString(36).padStart(7, '0')
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  external = false,
  timeShapeMinutes = false
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  const hasId = typeof frontmatter.id === 'string' && frontmatter.id
  const hasTitle = typeof frontmatter.title === 'string' && frontmatter.title
  // TaskNotes' storeTitleInFilename (default on) keeps the title only in the
  // filename, leaving frontmatter.title absent — fall back to the basename so
  // the task doesn't hydrate as 'Untitled'.
  const basename = filePath.split('/').pop()?.replace(/\.md$/, '') ?? 'Untitled'
  const task = mapRawToTask(
    frontmatter,
    {
      description: stripAutoGeneratedContent(body),
      filePath,
      ...(hasTitle ? {} : { title: basename }),
      // TaskNotes-created notes carry no PM `id`; give them a stable derived one.
      ...(hasId ? {} : { id: deriveTaskIdFromPath(filePath) }),
      ...(external ? { external: true } : {})
    },
    undefined,
    timeShapeMinutes
  )
  const subtaskIds = Array.isArray(frontmatter.subtaskIds) ? (frontmatter.subtaskIds as string[]) : []
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? '#8b72be',
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    // Copy containers: on the metadataCache fast path `frontmatter` is Obsidian's
    // live object, so sharing these arrays would let an in-place edit corrupt the cache.
    customFields: Array.isArray(frontmatter.customFields) ? [...(frontmatter.customFields as CustomFieldDef[])] : [],
    teamMembers: Array.isArray(frontmatter.teamMembers) ? [...(frontmatter.teamMembers as string[])] : [],
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    taskIndex: new Map()
  }
}

/** Read a project's settings overrides, dropping malformed fields. Absent or empty = inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  if (r.defaultView === 'table' || r.defaultView === 'gantt' || r.defaultView === 'kanban') {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.kanbanShowSubtasks === 'boolean') config.kanbanShowSubtasks = r.kanbanShowSubtasks
  if (typeof r.kanbanShowDescriptionPreview === 'boolean') {
    config.kanbanShowDescriptionPreview = r.kanbanShowDescriptionPreview
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: typeof s.color === 'string' ? s.color : '#8a94a0',
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: typeof p.color === 'string' ? p.color : '#8a94a0',
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}
